/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>

@class UIActionSheet, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ABBlockActionSheet : NSObject <UIActionSheetDelegate> {
	NSMutableArray* _blocks;
	UIActionSheet* _sheet;
	id _clickedButtonAtIndexBlock;
}
@property(copy, nonatomic) id clickedButtonAtIndexBlock;
@property(retain, nonatomic) UIActionSheet* sheet;
+(id)actionSheetWithTitle:(id)title;
-(unsigned)buttonCount;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)showFromRect:(CGRect)rect inView:(id)view animated:(BOOL)animated;
-(void)showFromBarButtonItem:(id)barButtonItem animated:(BOOL)animated;
-(void)showInView:(id)view;
-(int)addButtonWithTitle:(id)title block:(id)block;
-(void)setCancelButtonWithTitle:(id)title block:(id)block;
-(void)setDestructiveButtonWithTitle:(id)title block:(id)block;
-(void)dealloc;
-(id)initWithTitle:(id)title;
@end

