/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableArray;

@interface ABCodeEditorLayoutCache : NSObject {
	NSMutableDictionary* _objects;
	NSMutableArray* _accesses;
}
-(void)removeCacheEntriesGreaterThanOrEqualToLineIndex:(unsigned)lineIndex;
-(void)clear;
-(void)setCacheEntry:(id)entry forLineAtIndex:(unsigned)index;
-(void)linesRemovedAtIndex:(unsigned)index count:(unsigned)count;
-(void)linesInsertedAtIndex:(unsigned)index count:(unsigned)count;
-(void)removeCacheEntryForLineAtIndex:(unsigned)index;
-(void)removeCacheEntryForKey:(id)key;
-(id)cacheEntryForLineAtIndex:(unsigned)index;
-(unsigned)count;
-(void)dealloc;
-(id)init;
@end

