/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <QuartzCore/CALayer.h>
#import "Textastic-Structs.h"

@class CATransition, NSOperation;

@interface ABCodeEditorScalingViewTile : CALayer {
	NSOperation* _drawOperation;
	BOOL _drawSynchronously;
	CATransition* _fadeTransition;
	BOOL _useFadeTransition;
}
@property(assign, nonatomic) BOOL useFadeTransition;
-(id)actionForKey:(id)key;
-(void)drawTileInContext:(CGContextRef)context operation:(id)operation;
-(void)display;
-(void)setNeedsDisplayInRect:(CGRect)rect;
-(void)drawTile;
-(id)scalingView;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(void)cancelDrawOperation;
-(void)waitUntilDrawOperationIsFinished;
-(void)cancelDrawOperationInPreparationForWait;
-(id)init;
@end

