/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIApplication.h>

@class NSMutableSet;

@interface ABCodeEditorApplication : UIApplication {
	NSMutableSet* _nonRetainedDelegates;
}
-(void)sendEvent:(id)event;
-(id)stringFromEventFlags:(int)eventFlags;
-(id)stringFromEventType:(int)eventType;
-(void)removeKeyboardDelegate:(id)delegate;
-(void)addKeyboardDelegate:(id)delegate;
-(void)dealloc;
@end

