/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "Textastic-Structs.h"


@interface ABCodeEditorCaret : UIView {
}
-(void)setCursorFrame:(CGRect)frame;
-(void)stopBlinking;
-(void)startBlinking;
-(id)initWithFrame:(CGRect)frame;
@end

