/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface ABCodeCompletionEntry : NSObject {
	NSString* _string;
	NSString* _append;
	NSString* _replace;
	NSString* _partialString;
}
@property(copy, nonatomic) NSString* partialString;
@property(copy, nonatomic) NSString* replace;
@property(copy, nonatomic) NSString* append;
@property(copy, nonatomic) NSString* string;
-(int)compare:(id)compare;
-(id)description;
-(void)dealloc;
@end

