/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "Textastic-Structs.h"
#import <UIKit/UIScrollView.h>

@class ABCodeEditorContentView;

@interface ABCodeEditorView : UIScrollView <UIScrollViewDelegate> {
	BOOL _zooming;
	ABCodeEditorContentView* _editorContentView;
}
@property(retain, nonatomic) ABCodeEditorContentView* editorContentView;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewWillBeginDecelerating:(id)scrollView;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(BOOL)scrollViewShouldScrollToTop:(id)scrollView;
-(void)setContentOffsetPlusOne;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewDidEndZooming:(id)scrollView withView:(id)view atScale:(float)scale;
-(void)scrollViewDidZoom:(id)scrollView;
-(void)scrollViewWillBeginZooming:(id)scrollView withView:(id)view;
-(float)snapZoomScale:(float)scale;
-(float)fullScreenScale;
-(float)fullScreenScaleForCanvasSize:(CGSize)canvasSize;
-(id)zoomingGestureRecognizer;
-(void)editorSizeChanged;
-(void)adjustScaleTo:(float)to;
-(void)layoutSubviews;
-(id)viewForZoomingInScrollView:(id)scrollView;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(id)initWithFrame:(CGRect)frame theme:(id)theme;
@end

