/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class NSTextCheckingResult;

@interface ABCodeEditorSearchResult : NSObject {
	NSRange _foundRange;
	NSTextCheckingResult* _textCheckingResult;
}
@property(retain, nonatomic) NSTextCheckingResult* textCheckingResult;
@property(assign, nonatomic) NSRange foundRange;
+(id)searchResultWithFoundRange:(NSRange)foundRange;
-(void)dealloc;
-(id)initWithFoundRange:(NSRange)foundRange;
@end

