/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSOperation.h>

@class ABCodeEditorScalingViewTile;

@interface ABCodeEditorScalingViewTileDrawOperation : NSOperation {
	ABCodeEditorScalingViewTile* _tile;
	BOOL _drawSynchronously;
}
@property(assign, nonatomic) BOOL drawSynchronously;
@property(retain, nonatomic) ABCodeEditorScalingViewTile* tile;
-(void)main;
-(void)dealloc;
@end

