/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "Textastic-Structs.h"


@interface ABCodeEditorSnippetTabView : UIView {
	BOOL _range;
}
@property(assign, nonatomic, getter=isRange) BOOL range;
-(void)drawRect:(CGRect)rect;
-(void)stopBlinking;
-(void)startBlinking;
-(id)initWithFrame:(CGRect)frame;
@end

