/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABSyntaxScopeScorer, NSMutableSet, NSMutableArray, NSMutableDictionary;

@interface ABCodeCompletionCollection : NSObject {
	NSMutableArray* _contexts;
	NSMutableDictionary* _completionSets;
	NSMutableSet* _loadedUUIDs;
	ABSyntaxScopeScorer* _scopeScorer;
}
@property(readonly, assign, nonatomic) ABSyntaxScopeScorer* scopeScorer;
@property(readonly, assign, nonatomic) NSMutableDictionary* completionSets;
@property(readonly, assign, nonatomic) NSMutableArray* contexts;
@property(readonly, assign, nonatomic) NSMutableSet* loadedUUIDs;
+(id)sharedCodeCompletionCollection;
-(id)completionResultWithCompletionContexts:(id)completionContexts forLine:(id)line atPosition:(unsigned)position;
-(id)completionContextsForScope:(id)scope;
-(void)loadCodeCompletionDefinitionFile:(id)file;
-(void)loadContexts:(id)contexts;
-(void)loadCompletionSets:(id)sets;
-(void)loadCodeCompletionDefinitions;
-(void)loadCodeCompletionDefinitionsWithBasePath:(id)basePath;
-(void)dealloc;
-(id)init;
@end

