/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface ABCompressingTreeListNode : NSObject {
	ABCompressingTreeListNode* _left;
	ABCompressingTreeListNode* _right;
	ABCompressingTreeListNode* _parent;
	unsigned _count;
	unsigned _totalCount;
	BOOL _color;
	id _value;
}
@property(assign, nonatomic) unsigned totalCount;
@property(assign, nonatomic) unsigned count;
@property(retain, nonatomic) id value;
@property(assign, nonatomic) BOOL color;
@property(assign, nonatomic) ABCompressingTreeListNode* parent;
@property(retain, nonatomic) ABCompressingTreeListNode* right;
@property(retain, nonatomic) ABCompressingTreeListNode* left;
+(id)nodeWithValue:(id)value count:(unsigned)count;
-(id)description;
-(id)previousNode;
-(id)nextNode;
-(id)rightMost;
-(id)leftMost;
-(void)dealloc;
-(id)initWithValue:(id)value count:(unsigned)count;
@end

