/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIInputViewAudioFeedback.h"
#import <UIKit/UIView.h>

@class UIButton, UITapGestureRecognizer, ABCodeEditorContentView, UIImageView, NSTimer;

@interface ABCodeEditorNavigationWheel : UIView <UIInputViewAudioFeedback> {
	UIImageView* backgroundImageView;
	UITapGestureRecognizer* twoFingerTapGestureRecognizer;
	UIButton* buttonUp;
	UIButton* buttonDown;
	UIButton* buttonLeft;
	UIButton* buttonRight;
	UIButton* buttonSelectionStart;
	UIButton* buttonSelectionEnd;
	UIButton* buttonClose;
	UIButton* buttonMove;
	ABCodeEditorContentView* editorView;
	NSTimer* timerUp;
	NSTimer* timerDown;
	NSTimer* timerLeft;
	NSTimer* timerRight;
}
@property(readonly, assign, nonatomic) BOOL enableInputClicksWhenVisible;
@property(retain, nonatomic) ABCodeEditorContentView* editorView;
@property(retain, nonatomic) UIButton* buttonMove;
@property(retain, nonatomic) UIButton* buttonClose;
@property(retain, nonatomic) UIButton* buttonSelectionEnd;
@property(retain, nonatomic) UIButton* buttonSelectionStart;
@property(retain, nonatomic) UIButton* buttonRight;
@property(retain, nonatomic) UIButton* buttonLeft;
@property(retain, nonatomic) UIButton* buttonDown;
@property(retain, nonatomic) UIButton* buttonUp;
+(id)navigationWheelForEditor:(id)editor;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)awakeFromNib;
-(void)panGesture:(id)gesture;
-(void)touchUpInsideButton:(id)button;
-(void)displayOverlayWithString:(id)string;
-(void)pulseView:(id)view;
-(void)touchUpOutsideButton:(id)button;
-(void)scheduleShowEditMenu;
-(void)showEditMenu;
-(void)touchDownButton:(id)button;
-(void)setupMoveTransform:(BOOL)transform;
-(id)createArrowKeyTimer;
-(void)timerFired:(id)fired;
-(void)moveCursorInDirection:(int)direction;
-(void)twoFingerTap:(id)tap;
-(void)hide;
-(void)refreshButtonState;
-(void)stopAndFreeTimer:(id*)timer;
@end

