/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>

@class NSString, UIFont, NSTimer;

@interface ABCodeEditorOverlayView : UIView {
	NSString* text;
	UIFont* font;
	CGSize borderSize;
	double messageDisplayInterval;
	NSTimer* overlayTimer;
	CGSize cachedSuggestedSize;
	BOOL shouldHide;
}
@property(readonly, assign, nonatomic) BOOL isVisible;
@property(assign, nonatomic) double messageDisplayInterval;
@property(assign, nonatomic) CGSize borderSize;
@property(assign, nonatomic) float fontSize;
@property(retain, nonatomic) NSString* text;
+(void)displayTemporaryOverlayInView:(id)view withString:(id)string alignment:(int)alignment displayInterval:(double)interval;
+(void)displayTemporaryOverlayInView:(id)view withString:(id)string positionedForGestureRecognizer:(id)gestureRecognizer displayInterval:(double)interval;
+(void)displayTemporaryOverlayInView:(id)view withString:(id)string centeredAbovePoint:(CGPoint)point displayInterval:(double)interval;
+(void)displayTemporaryOverlayInView:(id)view withString:(id)string centeredAtPoint:(CGPoint)point displayInterval:(double)interval;
+(void)displayTemporaryOverlayInView:(id)view withString:(id)string avoidingTouchPoint:(CGPoint)point;
+(id)sharedTemporaryOverlay;
+(id)backgroundImage;
-(void)drawRect:(CGRect)rect;
-(void)centerAtPositionForGestureRecognizer:(id)gestureRecognizer inView:(id)view;
-(CGPoint)positionForTwoTouchGestureRecognizer:(id)twoTouchGestureRecognizer inView:(id)view;
-(void)useAlignment:(int)alignment withinBounds:(CGRect)bounds;
-(void)centerAbovePoint:(CGPoint)point withinBounds:(CGRect)bounds;
-(void)centerAtPoint:(CGPoint)point withOffset:(CGPoint)offset withinBounds:(CGRect)bounds;
-(void)avoidTouchPoint:(CGPoint)point withinBounds:(CGRect)bounds;
-(void)useSuggestedSize;
-(CGSize)suggestedSize;
-(void)setFrame:(CGRect)frame;
-(void)resetDefaults;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(void)_hideOverlayEffectDidStop:(id)_hideOverlayEffect finished:(id)finished context:(void*)context;
-(void)hideAnimated:(BOOL)animated;
-(void)hide;
-(void)displayInView:(id)view;
-(void)_temporaryOverlayTimerFired:(id)fired;
-(void)displayTemporarilyInView:(id)view;
@end

