/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"


@interface ABCodeEditorSnippetTabInterval : NSObject {
	unsigned _parent;
	NSRange _range;
}
@property(assign, nonatomic) unsigned length;
@property(assign, nonatomic) unsigned location;
@property(assign, nonatomic) NSRange range;
@property(assign, nonatomic) unsigned parent;
+(id)tabInterval;
-(NSRange)editorRangeWithInsertLocation:(unsigned)insertLocation;
@end

