/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIGestureRecognizer.h>
#import "Textastic-Structs.h"

@class NSMutableSet;

@interface ABCodeEditorSwipeGestureRecognizer : UIGestureRecognizer {
	NSMutableSet* _capturedTouches;
	double _startTimeStamp;
	CGPoint _gestureStartPoint;
	int _recognizedDirection;
	unsigned _recognizedTouches;
	unsigned _minimumNumberOfTouches;
	unsigned _maximumNumberOfTouches;
	double _maximumDuration;
}
@property(readonly, assign, nonatomic) int recognizedDirection;
@property(assign, nonatomic) double maximumDuration;
@property(assign, nonatomic) unsigned maximumNumberOfTouches;
@property(assign, nonatomic) unsigned minimumNumberOfTouches;
-(unsigned)numberOfTouches;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(double)durationOfGesture;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(CGPoint)viewLocationFromScreenLocation:(CGPoint)screenLocation;
-(CGPoint)screenLocationOfTouch:(id)touch;
-(void)setState:(int)state;
-(void)reset;
-(void)dealloc;
-(id)initWithTarget:(id)target action:(SEL)action;
@end

