/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface ABCodeEditorTemplate : NSObject {
	NSString* _name;
	NSString* _fileExtension;
	NSString* _scope;
	NSString* _snippet;
}
@property(copy, nonatomic) NSString* snippet;
@property(copy, nonatomic) NSString* scope;
@property(copy, nonatomic) NSString* fileExtension;
@property(copy, nonatomic) NSString* name;
-(void)dealloc;
@end

