/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UIInputViewAudioFeedback.h"
#import <UIKit/UIView.h>

@class NSMutableArray, UISegmentedControl, UIImageView;

__attribute__((visibility("hidden")))
@interface ABCodeEditorAccessoryView : UIView <UIInputViewAudioFeedback> {
	UIImageView* _backgroundImageView;
	NSMutableArray* _buttons;
	UISegmentedControl* _undoSegmentedControl;
}
@property(readonly, assign, nonatomic) BOOL enableInputClicksWhenVisible;
@property(readonly, assign, nonatomic) UISegmentedControl* undoSegmentedControl;
-(void)dealloc;
-(void)setFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
-(void)layoutButtonsWithInterfaceOrientation:(int)interfaceOrientation;
-(void)dismissAction:(id)action;
-(id)contentView;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(BOOL)isIOS5;
@end

