/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>
#import "UIGestureRecognizerDelegate.h"

@class UILongPressGestureRecognizer, UIPanGestureRecognizer;

@interface ABCodeEditorTextThumb : UIView <UIGestureRecognizerDelegate> {
	float ascent;
	float width;
	CGPoint touchdownPoint;
	CGPoint contentOffset;
	BOOL isEndThumb;
	UIPanGestureRecognizer* dragMe;
	UILongPressGestureRecognizer* longPress;
}
@property(assign, nonatomic) BOOL isEndThumb;
-(void)longPressGesture:(id)gesture;
-(void)_dragged:(id)dragged;
-(void)drawRect:(CGRect)rect;
-(void)setHidden:(BOOL)hidden;
-(BOOL)canBecomeFirstResponder;
-(void)setCaretRectangle:(CGRect)rectangle;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
@end

