/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UITextRange.h>


@interface ABCodeEditorTextRange : UITextRange {
	NSRange _range;
}
@property(assign, nonatomic) NSRange range;
+(id)rangeWithNSRange:(NSRange)nsrange;
-(BOOL)isEqualToTextRange:(id)textRange;
-(id)description;
-(BOOL)isEmpty;
-(id)end;
-(id)start;
@end

