/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "SMTEDelegateController.h"


@interface ABCodeEditorTextExpanderDelegateController : SMTEDelegateController {
}
-(void)setTextView:(id)view textViewText:(id)text oldRange:(NSRange)range oldText:(id)text4 newRange:(NSRange)range5 newText:(id)text6;
@end

