/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITextPosition.h>


@interface ABCodeEditorTextPosition : UITextPosition {
	unsigned _index;
}
@property(assign, nonatomic) unsigned index;
+(id)positionWithIndex:(unsigned)index;
-(id)description;
-(int)compare:(id)compare;
@end

