/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface ABCodeCompletionSet : NSObject {
	NSString* _name;
	NSArray* _entries;
}
@property(copy, nonatomic) NSArray* entries;
@property(copy, nonatomic) NSString* name;
-(void)dealloc;
@end

