/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ABCodeCompletionResult, UIFont, UITableView, ABCodeEditorContentView;

@interface ABCodeCompletionView : UIView <UITableViewDelegate, UITableViewDataSource> {
	UITableView* _tableView;
	ABCodeEditorContentView* _codeEditorContentView;
	UIFont* _entryFont;
	ABCodeCompletionResult* _completionResult;
}
@property(retain, nonatomic) ABCodeCompletionResult* completionResult;
@property(retain, nonatomic) UIFont* entryFont;
@property(assign, nonatomic) ABCodeEditorContentView* codeEditorContentView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)selectPreviousCompletion;
-(BOOL)selectNextCompletion;
-(BOOL)acceptCompletion;
-(BOOL)acceptCompletionAtIndexPath:(id)indexPath;
-(void)loadCodeCompletionResult:(id)result;
-(void)adjustSize;
-(void)dealloc;
-(id)initWithCodeEditorContentView:(id)codeEditorContentView;
@end

