/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

@interface ABCodeEditorSnippetTransformation : NSObject {
	unsigned _intervalIndex;
	NSString* _regExString;
	NSString* _format;
	BOOL _global;
}
@property(assign, nonatomic, getter=isGlobal) BOOL global;
@property(copy, nonatomic) NSString* format;
@property(copy, nonatomic) NSString* regExString;
@property(assign, nonatomic) unsigned intervalIndex;
+(id)transformation;
-(void)dealloc;
@end

