/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface ABCodeEditorKeyboardEvent : NSObject {
	unsigned short _keyCode;
	unsigned short _character;
	int _modifierFlags;
}
@property(assign, nonatomic) int modifierFlags;
@property(assign, nonatomic) unsigned short character;
@property(assign, nonatomic) unsigned short keyCode;
+(id)keyboardEventWithKeyCode:(unsigned short)keyCode character:(unsigned short)character modifierFlags:(int)flags;
-(id)initWithKeyCode:(unsigned short)keyCode character:(unsigned short)character modifierFlags:(int)flags;
@end

