/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface ABCodeEditorTemplateCategory : NSObject {
	NSString* _name;
	NSMutableArray* _templates;
}
@property(readonly, assign, nonatomic) NSMutableArray* templates;
@property(copy, nonatomic) NSString* name;
-(void)dealloc;
-(id)init;
@end

