/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UIInputViewAudioFeedback.h"
#import <UIKit/UIView.h>

@class UIImageView, UIPanGestureRecognizer;

__attribute__((visibility("hidden")))
@interface ABCodeEditorCursorControl : UIView <UIInputViewAudioFeedback> {
	UIImageView* _backgroundImageView;
	BOOL _pressed;
	BOOL _didDetermineDirection;
	BOOL _moveSelectionStart;
	UIPanGestureRecognizer* _panGestureRecognizer;
	CGPoint _movementAccumulator;
	BOOL _didMove;
	CGRect _unpressedFrame;
}
@property(readonly, assign, nonatomic) BOOL enableInputClicksWhenVisible;
-(void)handlePanGesture:(id)gesture;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(float)selectionYChangeVelocityFromYTouchVelocity:(float)ytouchVelocity;
-(float)selectionXChangeVelocityFromXTouchVelocity:(float)xtouchVelocity;
-(void)moveCursorInDirection:(int)direction offset:(int)offset;
-(void)scheduleShowEditMenu;
-(void)showEditMenu;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

