/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"


@interface ABDocumentLine : NSObject {
	BOOL _deleted;
	unsigned _totalLength;
	unsigned char _delimiterLength;
	ABDocumentLine* _left;
	ABDocumentLine* _right;
	ABDocumentLine* _parent;
	BOOL _color;
	unsigned _nodeTotalCount;
	unsigned _nodeTotalLength;
}
@property(assign, nonatomic) unsigned nodeTotalLength;
@property(assign, nonatomic) unsigned nodeTotalCount;
@property(assign, nonatomic) BOOL color;
@property(assign, nonatomic) ABDocumentLine* parent;
@property(retain, nonatomic) ABDocumentLine* right;
@property(retain, nonatomic) ABDocumentLine* left;
@property(assign, nonatomic, getter=isDeleted) BOOL deleted;
@property(assign, nonatomic) unsigned char delimiterLength;
@property(assign, nonatomic) unsigned totalLength;
@property(readonly, assign, nonatomic) unsigned length;
@property(readonly, assign, nonatomic) NSRange range;
@property(readonly, assign, nonatomic) unsigned endLocation;
@property(readonly, assign, nonatomic) unsigned location;
@property(readonly, assign, nonatomic) unsigned lineNumber;
-(id)description;
-(id)previousLine;
-(id)nextLine;
-(id)rightMost;
-(id)leftMost;
-(id)prepareDocumentLineNode;
-(void)dealloc;
-(id)init;
@end

