/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABTextDocument, ABDocumentLine;

@interface ABDocumentLineTree : NSObject {
	ABTextDocument* _textDocument;
	ABDocumentLine* _root;
}
@property(retain, nonatomic) ABDocumentLine* root;
@property(readonly, assign, nonatomic) ABTextDocument* textDocument;
+(id)siblingOfNode:(id)node parentNode:(id)node2;
+(id)siblingOfNode:(id)node;
+(unsigned)locationOfDocumentLine:(id)documentLine;
+(unsigned)indexOfDocumentLine:(id)documentLine;
+(unsigned)getTreeHeightForSize:(unsigned)size;
+(void)updateAfterRightRotationOfNode:(id)node;
+(void)updateAfterLeftRotationOfNode:(id)node;
+(void)updateAfterChildrenChangeOfNode:(id)node;
-(void)rightRotateNode:(id)node;
-(void)leftRotateNode:(id)node;
-(void)replaceNode:(id)node with:(id)with;
-(void)fixTreeOnDeleteAtNode:(id)node parentNode:(id)node2;
-(void)removeNode:(id)node;
-(void)fixTreeOnInsertAtNode:(id)node;
-(void)insertLine:(id)line rightOf:(id)of;
-(void)insertLine:(id)line leftOf:(id)of;
-(id)description;
-(void)appendDescriptionOfNode:(id)node toString:(id)string withIndent:(unsigned)indent;
-(void)insertLine:(id)line after:(id)after;
-(id)lineInsertedAfter:(id)after withLength:(unsigned)length;
-(void)removeLine:(id)line;
-(unsigned)lineCount;
-(id)documentLineFromLocation:(unsigned)location;
-(id)documentLineAtIndex:(unsigned)index;
-(void)rebuildTreeWithDocumentLines:(id)documentLines;
-(id)buildTreeWithNodes:(id)nodes start:(unsigned)start end:(unsigned)end subtreeHeight:(unsigned)height;
-(void)dealloc;
-(id)initWithTextDocument:(id)textDocument;
@end

