/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABSyntaxParserDelegate.h"
#import "ABSyntaxParserDataSource.h"
#import <Foundation/NSObject.h>

@class ABSyntaxTheme, ABImmutableStack, ABSyntaxParser, ABScopedLine, ABScopeTreeNode, ABCompressingTreeList, ABScopeTree, ABDocumentLine, ABTextDocument, NSNumber, ABSyntaxNode;

@interface ABDocumentHighlighter : NSObject <ABSyntaxParserDelegate, ABSyntaxParserDataSource> {
	ABCompressingTreeList* _storedSpanStacks;
	ABCompressingTreeList* _isValidTreeList;
	ABCompressingTreeList* _storedScope;
	ABCompressingTreeList* _highlightedLines;
	NSNumber* _valid;
	NSNumber* _invalid;
	ABTextDocument* _document;
	ABSyntaxNode* _baseSyntaxNode;
	ABSyntaxTheme* _theme;
	BOOL _highlighting;
	BOOL _highlightingUpTo;
	unsigned _firstInvalidLine;
	ABImmutableStack* _initialSpanStack;
	ABScopeTree* _scopeTree;
	unsigned _lastPositionInLine;
	ABScopedLine* _highlightedLine;
	ABDocumentLine* _currentDocumentLine;
	unsigned _currentLineLength;
	unsigned _currentLineNumber;
	ABSyntaxParser* _parser;
	ABImmutableStack* _endOfLineSpanStack;
	ABImmutableStack* _lastSyntaxNodeStack;
	ABScopeTreeNode* _currentScope;
	BOOL _needAddAttributesForTabs;
}
@property(readonly, assign, nonatomic) ABScopeTree* scopeTree;
@property(readonly, assign, nonatomic) ABSyntaxNode* syntaxNode;
-(id)symbolList;
-(void)syntaxParser:(id)parser didEndParsingWithScope:(id)scope;
-(void)syntaxParser:(id)parser didStartParsingWithScope:(id)scope;
-(void)syntaxParser:(id)parser didEndScope:(id)scope atPositionInLine:(unsigned)line;
-(void)syntaxParser:(id)parser didStartScope:(id)scope atPositionInLine:(unsigned)line;
-(void)syntaxParser:(id)parser didEndLineWithStack:(id)stack;
-(void)syntaxParser:(id)parser didStartLine:(id)line;
-(void)prepareScope;
-(id)nextLineOrNilForSyntaxParser:(id)syntaxParser;
-(void)highlightDocumentLineAndUpdateTreeList:(id)list lineNumber:(unsigned)number;
-(BOOL)spanStack:(id)stack isEqualTo:(id)to;
-(id)attributedStringForLineNumber:(unsigned)lineNumber textRectWidth:(float)width;
-(void)addAttributeForTabCharactersInAttributedString:(id)attributedString;
-(id)highlightedLineIfAvailableWithNumber:(unsigned)number;
-(unsigned)highlightUpToNumberOfLines:(unsigned)lines timeLimit:(double)limit withOperation:(id)operation;
-(void)highlightUpToLineNumber:(unsigned)lineNumber withOperationOrNil:(id)operationOrNil;
-(id)highlightLineWithNumber:(unsigned)number;
-(void)clearHighlightedLineCache;
-(void)invalidateHighlighting;
-(void)didRebuildDocumentNotification:(id)notification;
-(void)didInsertLine:(id)line;
-(void)willChangeLineLength:(id)length;
-(void)willRemoveLine:(id)line;
-(void)checkIsHighlighting;
-(void)setTheme:(id)theme;
-(void)dealloc;
-(id)initWithTextDocument:(id)textDocument syntaxNode:(id)node theme:(id)theme;
@end

