/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class ABTextDocument, ABHeightTreeNode;

@interface ABHeightTree : NSObject {
	ABHeightTreeNode* _root;
	ABTextDocument* _document;
	float _defaultLineHeight;
}
@property(assign, nonatomic) float defaultLineHeight;
@property(retain, nonatomic) ABTextDocument* document;
@property(retain, nonatomic) ABHeightTreeNode* root;
-(id)description;
-(void)appendDescriptionOfNode:(id)node toString:(id)string withIndent:(unsigned)indent;
-(void)rightRotateNode:(id)node;
-(void)leftRotateNode:(id)node;
-(void)replaceNode:(id)node with:(id)with;
-(id)nodeOfDocumentLine:(id)documentLine;
-(unsigned)count;
-(id)nodeAtIndex:(unsigned*)index;
-(id)siblingOfNode:(id)node parentNode:(id)node2;
-(id)siblingOfNode:(id)node;
-(void)fixTreeOnDeleteAtNode:(id)node parentNode:(id)node2;
-(void)removeNode:(id)node;
-(void)fixTreeOnInsertAtNode:(id)node;
-(void)updateAugmentedDataOfNode:(id)node;
-(void)insertNode:(id)node rightOf:(id)of;
-(void)insertNode:(id)node leftOf:(id)of;
-(void)insertNode:(id)node after:(id)after;
-(void)insertNode:(id)node before:(id)before;
-(void)rebuildDocument;
-(float)totalHeight;
-(void)setHeight:(float)height ofLineAtIndex:(unsigned)index;
-(void)setHeight:(float)height ofDocumentLine:(id)documentLine;
-(float)yOffsetOfLineAtIndex:(unsigned)index;
-(float)yOffsetOfDocumentLine:(id)documentLine;
-(int)lineIndexAtYOffset:(float*)yoffset;
-(unsigned)indexOfNode:(id)node;
-(id)nodeAtYOffset:(float*)yoffset;
-(float)heightOfLineAtIndex:(unsigned)index;
-(float)heightOfDocumentLine:(id)documentLine;
-(void)didRebuildDocumentNotification:(id)notification;
-(void)didInsertLine:(id)line;
-(void)removeObjectsInRange:(NSRange)range;
-(void)insertHeight:(float)height inRange:(NSRange)range;
-(void)willRemoveLine:(id)line;
-(void)dealloc;
-(id)initWithDocument:(id)document defaultLineHeight:(float)height;
@end

