/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface ABHeightTreeNode : NSObject {
	ABHeightTreeNode* _left;
	ABHeightTreeNode* _right;
	ABHeightTreeNode* _parent;
	BOOL _color;
	unsigned _totalCount;
	float _height;
	float _totalHeight;
	unsigned _count;
}
@property(assign, nonatomic) unsigned count;
@property(assign, nonatomic) float totalHeight;
@property(assign, nonatomic) float height;
@property(assign, nonatomic) unsigned totalCount;
@property(assign, nonatomic) BOOL color;
@property(assign, nonatomic) ABHeightTreeNode* parent;
@property(retain, nonatomic) ABHeightTreeNode* right;
@property(retain, nonatomic) ABHeightTreeNode* left;
+(id)nodeWithCount:(unsigned)count height:(float)height;
-(id)description;
-(id)previousNode;
-(id)nextNode;
-(id)rightMost;
-(id)leftMost;
-(void)dealloc;
-(id)initWithCount:(unsigned)count height:(float)height;
@end

