/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCViewControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "SCTableViewCell.h"

@class UIPopoverController, UIImage, UIImagePickerController;

__attribute__((visibility("hidden")))
@interface ABImagePickerCell : SCTableViewCell <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIActionSheetDelegate, SCViewControllerDelegate> {
	UIImage* selectedImage;
	UIImage* placeholderImage;
	UIImagePickerController* imagePickerController;
	BOOL askForSourceType;
	UIPopoverController* popover;
}
@property(assign, nonatomic) BOOL askForSourceType;
@property(retain, nonatomic) UIImage* placeholderImage;
@property(retain, nonatomic) UIImage* selectedImage;
@property(readonly, assign, nonatomic) UIImagePickerController* imagePickerController;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withImagePropertyName:(id)imagePropertyName;
-(void)viewControllerWillDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerWillAppear:(id)viewController;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)displayImagePicker;
-(void)displayImageInDetailView;
-(void)didSelectCell;
-(BOOL)getValueIsValid;
-(void)commitChanges;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withImagePropertyName:(id)imagePropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(float)height;
@end

