/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>


@interface ABIntegerArrayBase : NSObject {
	CFArrayRef _array;
}
+(id)array;
-(void)removeAllValues;
-(void)removeValueAtIndex:(unsigned)index;
-(unsigned)count;
-(void)dealloc;
-(id)init;
@end

