/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABIntegerArrayBase.h"


@interface ABIntegerArray : ABIntegerArrayBase {
}
-(void)replaceValueAtIndex:(unsigned)index withInteger:(int)integer;
-(void)insertInteger:(int)integer atIndex:(unsigned)index;
-(void)addInteger:(int)integer;
-(int)integerAtIndex:(unsigned)index;
@end

