/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class ABTextDocument, ABDocumentLineTree;

@interface ABLineManager : NSObject {
	ABTextDocument* _document;
	ABDocumentLineTree* _documentLineTree;
}
@property(assign, nonatomic) ABDocumentLineTree* documentLineTree;
@property(assign, nonatomic) ABTextDocument* document;
-(id)documentLine:(id)line setLineLength:(unsigned)length;
-(id)lineInsertedAfter:(id)after withLength:(unsigned)length;
-(void)insertText:(id)text atLocation:(unsigned)location;
-(void)removeLine:(id)line;
-(void)removeRange:(NSRange)range;
-(void)rebuild;
-(void)dealloc;
-(id)initWithTextDocument:(id)textDocument documentLineTree:(id)tree;
@end

