/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIWindow.h>


__attribute__((visibility("hidden")))
@interface ABPassKeyWindow : UIWindow {
	UIWindow* oldKeyWindow;
}
@property(retain, nonatomic) UIWindow* oldKeyWindow;
-(void)dealloc;
-(void)resignKeyWindow;
-(void)makeKeyAndVisible;
@end

