/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UITextFieldDelegate.h"
#import <UIKit/UIViewController.h>

@class UIView, UIButton, UITextField;

__attribute__((visibility("hidden")))
@interface ABPassKeyViewController : UIViewController <UITextFieldDelegate> {
	UIButton* unlockButton;
	UITextField* passcodeTextField;
	UIView* containerView;
}
@property(retain, nonatomic) UIView* containerView;
@property(retain, nonatomic) UITextField* passcodeTextField;
@property(retain, nonatomic) UIButton* unlockButton;
+(BOOL)currentlyVisible;
+(void)show;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)unlockButtonAction:(id)action;
-(void)dismiss;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)viewWillAppear:(BOOL)view;
-(void)setContainerViewYForOrientation:(int)orientation;
@end

