/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSTextCheckingResult, OnigResult, NSMutableString;

@interface ABReplaceStringParserState : NSObject {
	BOOL _didAllocateTemplateCharacters;
	NSString* _source;
	OnigResult* _regExResult;
	NSTextCheckingResult* _textCheckingResult;
	BOOL _upperCase;
	BOOL _lowerCase;
	BOOL _caseChar;
	BOOL _caseText;
	NSMutableString* _replacementText;
	int _offset;
	unsigned _templateLength;
	unsigned short* _templateCharacters;
}
@property(assign, nonatomic) unsigned templateLength;
@property(assign, nonatomic) unsigned short* templateCharacters;
@property(assign, nonatomic) int offset;
@property(retain, nonatomic) NSMutableString* replacementText;
@property(assign, nonatomic) BOOL caseText;
@property(assign, nonatomic) BOOL caseChar;
@property(assign, nonatomic) BOOL lowerCase;
@property(assign, nonatomic) BOOL upperCase;
@property(retain, nonatomic) NSTextCheckingResult* textCheckingResult;
@property(retain, nonatomic) OnigResult* regExResult;
@property(retain, nonatomic) NSString* source;
-(void)appendCharacter:(unsigned short)character;
-(void)dealloc;
-(void)setTemplateString:(id)string;
@end

