/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"


@interface ABReplaceStringParser : NSObject {
}
+(id)replacementStringForResult:(id)result inString:(id)string offset:(int)offset templateCharacters:(unsigned short*)characters templateLength:(unsigned)length;
+(id)replacementStringForResult:(id)result inString:(id)string offset:(int)offset template:(id)aTemplate;
+(id)replacementStringWithSourceString:(id)sourceString regExResult:(id)result replacementFormatString:(id)string;
+(void)_replaceWithRange:(NSRange)range state:(id)state;
@end

