/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface ABRoundedRects : NSObject {
	NSMutableArray* _rects;
}
-(void)drawInContext:(CGContextRef)context withFillColor:(id)fillColor strokeColor:(id)color;
-(void)addRect:(CGRect)rect;
-(void)dealloc;
@end

