/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface ABScopeSelector : NSObject {
	BOOL _didCompile;
	NSArray* _scopeSelectorOrParts;
	NSString* _scopeSelectorString;
}
@property(copy, nonatomic) NSString* scopeSelectorString;
@property(retain, nonatomic) NSArray* scopeSelectorOrParts;
+(id)scopeSelectorWithString:(id)string;
+(void)initialize;
-(void)dealloc;
-(id)initWithString:(id)string;
-(void)compile;
-(id)andSplitString:(id)string;
@end

