/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABScopeTreeNode;

@interface ABScopeTree : NSObject {
	ABScopeTreeNode* _rootNode;
}
@property(readonly, assign, nonatomic) ABScopeTreeNode* rootNode;
-(void)dealloc;
-(void)clearAttributedStringAttributes;
-(id)init;
@end

