/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABScopeTreeNode;

@interface ABScopedLineSegment : NSObject {
	unsigned _length;
	ABScopeTreeNode* _scopeTreeNode;
}
@property(readonly, assign, nonatomic) ABScopeTreeNode* scopeTreeNode;
@property(readonly, assign, nonatomic) unsigned length;
-(void)dealloc;
-(id)description;
-(id)initWithLength:(unsigned)length scopeTreeNode:(id)node;
@end

