/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>

@class NSString;

@interface ABSwipeButton : UIView {
	id _actionBlock;
	NSString* _titles[5];
	BOOL _pressed;
	int _activePosition;
	CGPoint _startTouchPosition;
	CGRect _unpressedFrame;
}
+(id)activeFont;
+(id)smallKeyFont;
+(id)bigKeyFont;
+(id)keyFont;
+(id)pressedBackgroundImage;
+(id)backgroundImage;
+(BOOL)isiPad;
-(void)drawRect:(CGRect)rect;
-(void)drawPosition:(int)position inRect:(CGRect)rect;
-(void)drawForwardDeleteAt:(CGPoint)at scale:(float)scale;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesMoved:(id)moved withEvent:(id)event;
-(void)setActivePosition:(int)position;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)setActionBlock:(id)block;
-(void)setTitle:(id)title forPosition:(int)position;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

