/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class ABSyntaxDefinitionCollection, NSString, OnigRegexp, NSDictionary, NSArray;

@interface ABSyntaxNode : NSObject {
	BOOL _didParsePatterns;
	BOOL _didParseRepository;
	BOOL _didCompileExpressions;
	ABSyntaxNode* rootSyntaxNode;
	ABSyntaxDefinitionCollection* syntaxDefinitionCollection;
	OnigRegexp* _firstLineMatch;
	OnigRegexp* _match;
	OnigRegexp* _begin;
	NSString* _firstLineMatchString;
	NSString* _matchString;
	NSString* _beginString;
	NSArray* _rawPatternsArray;
	NSDictionary* _rawRepositoryDictionary;
	NSString* uuid;
	NSString* name;
	NSString* contentName;
	NSString* end;
	NSString* scopeName;
	NSArray* captures;
	NSArray* beginCaptures;
	NSArray* endCaptures;
	NSDictionary* _repository;
	NSArray* _patterns;
	NSArray* fileTypes;
	OnigRegexp* endRegEx;
	BOOL applyEndPatternLast;
	XXStruct_DaUm_C _averageMatchDistance;
}
@property(assign, nonatomic) XXStruct_DaUm_C averageMatchDistance;
@property(assign, nonatomic) BOOL applyEndPatternLast;
@property(retain, nonatomic) NSArray* fileTypes;
@property(retain, nonatomic) NSArray* rawPatternsArray;
@property(retain, nonatomic) NSArray* patterns;
@property(retain, nonatomic) NSDictionary* rawRepositoryDictionary;
@property(retain, nonatomic) NSDictionary* repository;
@property(retain, nonatomic) NSArray* endCaptures;
@property(retain, nonatomic) NSArray* beginCaptures;
@property(retain, nonatomic) NSArray* captures;
@property(copy, nonatomic) NSString* scopeName;
@property(copy, nonatomic) NSString* uuid;
@property(copy, nonatomic) NSString* end;
@property(copy, nonatomic) NSString* contentName;
@property(copy, nonatomic) NSString* name;
@property(retain, nonatomic) OnigRegexp* endRegEx;
@property(retain, nonatomic) OnigRegexp* match;
@property(retain, nonatomic) OnigRegexp* begin;
@property(retain, nonatomic) OnigRegexp* firstLineMatch;
@property(copy, nonatomic) NSString* matchString;
@property(copy, nonatomic) NSString* beginString;
@property(copy, nonatomic) NSString* firstLineMatchString;
@property(readonly, assign, nonatomic) ABSyntaxDefinitionCollection* syntaxDefinitionCollection;
@property(readonly, assign, nonatomic) ABSyntaxNode* rootSyntaxNode;
+(id)optimizePattern:(id)pattern;
+(void)rebuildPattern:(id)pattern withDictionary:(id)dictionary;
-(void)dealloc;
-(id)initWithSyntaxDefinitionDictionary:(id)syntaxDefinitionDictionary rootSyntaxNode:(id)node syntaxDefinitionCollection:(id)collection;
-(id)parseCaptures:(id)captures;
-(void)parsePatterns:(id)patterns;
-(void)parseRepository:(id)repository;
-(id)description;
-(void)_compileExpressions;
@end

