/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIImage, ABScopeSelector;

__attribute__((visibility("hidden")))
@interface ABSymbolMappingEntry : NSObject {
	ABScopeSelector* _scopeSelector;
	UIImage* _image;
}
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) ABScopeSelector* scopeSelector;
-(void)dealloc;
@end

