/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, UIColor, NSDictionary, ABSyntaxTheme, ABScopeSelector;

@interface ABSyntaxStyle : NSObject {
	ABSyntaxTheme* _theme;
	NSString* _name;
	ABScopeSelector* _scopeSelector;
	UIColor* _backgroundColor;
	UIColor* _foregroundColor;
	unsigned _fontStyle;
	NSDictionary* _attributedStringAttributes;
}
@property(readonly, assign, nonatomic) NSDictionary* attributedStringAttributes;
@property(assign, nonatomic) unsigned fontStyle;
@property(retain, nonatomic) UIColor* foregroundColor;
@property(retain, nonatomic) UIColor* backgroundColor;
@property(retain, nonatomic) ABScopeSelector* scopeSelector;
@property(copy, nonatomic) NSString* name;
@property(assign, nonatomic) ABSyntaxTheme* theme;
+(id)syntaxStyleWithTheme:(id)theme name:(id)name scopeSelector:(id)selector backgroundColor:(id)color foregroundColor:(id)color5 fontStyle:(unsigned)style;
-(void)resetAttributedStringAttributes;
-(void)dealloc;
-(id)initWithTheme:(id)theme name:(id)name scopeSelector:(id)selector backgroundColor:(id)color foregroundColor:(id)color5 fontStyle:(unsigned)style;
@end

