/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableArray, ABSyntaxScopeScorer;

@interface ABSyntaxPreferences : NSObject {
	ABSyntaxScopeScorer* _scopeScorer;
	NSMutableDictionary* _scopeDictionary;
	NSMutableArray* _symbolListPreferences;
}
@property(readonly, assign, nonatomic) ABSyntaxScopeScorer* scopeScorer;
-(BOOL)symbolListPreference:(id)preference matchesScope:(id)scope;
-(id)symbolListPreferenceForScope:(id)scope;
-(id)bestMatchForScope:(id)scope preferenceArray:(id)array cacheDictionary:(id)dictionary dictionaryKey:(id)key;
-(void)loadSyntaxPreference:(id)preference;
-(void)dealloc;
-(id)init;
@end

