/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class ABScopeSelector, NSString;

@interface ABSyntaxSymbolListPreference : NSObject {
	NSString* _name;
	ABScopeSelector* _scopeSelector;
	NSString* _symbolTransformation;
	BOOL _showInSymbolList;
}
@property(assign, nonatomic) BOOL showInSymbolList;
@property(copy, nonatomic) NSString* symbolTransformation;
@property(retain, nonatomic) ABScopeSelector* scopeSelector;
@property(copy, nonatomic) NSString* name;
-(id)transformSymbolString:(id)string;
-(id)description;
-(void)dealloc;
@end

