/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


@interface ABSyntaxScopeScorer : NSObject {
}
-(BOOL)scopeSelectorString:(id)string matchesScopeString:(id)string2;
-(double)scoreOfScopeSelectorString:(id)scopeSelectorString withReferenceScopeString:(id)referenceScopeString;
-(BOOL)scopeSelector:(id)selector matchesScope:(id)scope;
-(double)scoreOfScopeSelector:(id)scopeSelector withReferenceScope:(id)referenceScope;
-(double)scoreSearchArray:(id)array referenceScope:(id)scope;
-(unsigned)countOfSubstring:(id)substring inString:(id)string;
@end

