/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ABSyntaxParserDelegate <NSObject>
-(void)syntaxParser:(id)parser didEndParsingWithScope:(id)scope;
-(void)syntaxParser:(id)parser didStartParsingWithScope:(id)scope;
-(void)syntaxParser:(id)parser didEndScope:(id)scope atPositionInLine:(unsigned)line;
-(void)syntaxParser:(id)parser didStartScope:(id)scope atPositionInLine:(unsigned)line;
-(void)syntaxParser:(id)parser didEndLineWithStack:(id)stack;
-(void)syntaxParser:(id)parser didStartLine:(id)line;
@end

