/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class ABScopeTreeNode, NSString;

@interface ABSymbolListItem : NSObject {
	NSString* _symbol;
	unsigned _lineNumber;
	ABScopeTreeNode* _scopeTreeNode;
	NSRange _range;
}
@property(assign, nonatomic) NSRange range;
@property(retain, nonatomic) ABScopeTreeNode* scopeTreeNode;
@property(assign, nonatomic) unsigned lineNumber;
@property(copy, nonatomic) NSString* symbol;
-(void)dealloc;
@end

