/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableSet, ABSyntaxPreferences, NSMutableDictionary, ABSyntaxNode;

@interface ABSyntaxDefinitionCollection : NSObject {
	NSMutableDictionary* _syntaxDefinitions;
	ABSyntaxNode* _currentBaseNode;
	NSMutableDictionary* _themes;
	ABSyntaxPreferences* _preferences;
	NSMutableSet* _loadedBundleUUIDs;
}
@property(retain, nonatomic) ABSyntaxNode* currentBaseNode;
@property(readonly, assign, nonatomic) ABSyntaxPreferences* preferences;
@property(readonly, assign, nonatomic) NSMutableSet* loadedBundleUUIDs;
@property(readonly, assign, nonatomic) NSMutableDictionary* themes;
@property(readonly, assign, nonatomic) NSMutableDictionary* syntaxDefinitions;
+(id)documentsDirectory;
+(id)sharedSyntaxDefinitionCollection;
-(id)rootSyntaxNodeForScopeName:(id)scopeName;
-(void)loadSyntaxDefinitions;
-(void)loadThemesFromBasePath:(id)basePath;
-(void)loadBundlesFromBasePath:(id)basePath;
-(void)loadTheme:(id)theme;
-(void)loadSyntaxDefinitionFile:(id)file;
-(void)userDidSelectSyntaxNode:(id)user forFile:(id)file;
-(id)guessSyntaxNodeForFile:(id)file;
-(void)dealloc;
-(id)init;
@end

