/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class OnigResult, ABSyntaxNode;

@interface ABSyntaxParserStackEntry : NSObject {
	ABSyntaxNode* _syntaxNode;
	OnigResult* _matchResult;
}
@property(retain, nonatomic) OnigResult* matchResult;
@property(retain, nonatomic) ABSyntaxNode* syntaxNode;
+(id)syntaxParserEntryWithSyntaxNode:(id)syntaxNode matchResult:(id)result;
-(void)dealloc;
-(BOOL)isEqualToSyntaxParserStackEntry:(id)syntaxParserStackEntry;
-(id)initWithSyntaxNode:(id)syntaxNode matchResult:(id)result;
@end

