/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class ABSyntaxScopeScorer, NSString, UIColor, NSMutableDictionary, NSDictionary, NSArray;

@interface ABSyntaxTheme : NSObject {
	ABSyntaxScopeScorer* _scopeScorer;
	NSMutableDictionary* _bestStyleDictionary;
	UIColor* backgroundColor;
	UIColor* foregroundColor;
	UIColor* caretColor;
	UIColor* selectionColor;
	UIColor* invisiblesColor;
	UIColor* lineHighlightColor;
	UIColor* searchHighlightColor;
	UIColor* bracketHighlightColor;
	UIColor* gutterColor;
	UIColor* multiEditHighlightColor;
	NSArray* _styles;
	NSString* _name;
	NSDictionary* _attributedStringAttributes;
	CTFontRef _normalFont;
	CTFontRef _italicFont;
	CTFontRef _boldFont;
	CTFontRef _boldItalicFont;
	CGSize _characterSize;
	unsigned _tabSize;
}
@property(assign, nonatomic) unsigned tabSize;
@property(assign, nonatomic) CGSize characterSize;
@property(readonly, assign, nonatomic) CTFontRef boldItalicFont;
@property(readonly, assign, nonatomic) CTFontRef boldFont;
@property(readonly, assign, nonatomic) CTFontRef italicFont;
@property(readonly, assign, nonatomic) CTFontRef normalFont;
@property(readonly, assign) NSDictionary* attributedStringAttributes;
@property(retain, nonatomic) NSArray* styles;
@property(retain, nonatomic) UIColor* multiEditHighlightColor;
@property(retain, nonatomic) UIColor* gutterColor;
@property(retain, nonatomic) UIColor* bracketHighlightColor;
@property(retain, nonatomic) UIColor* searchHighlightColor;
@property(retain, nonatomic) UIColor* lineHighlightColor;
@property(retain, nonatomic) UIColor* invisiblesColor;
@property(retain, nonatomic) UIColor* selectionColor;
@property(retain, nonatomic) UIColor* caretColor;
@property(retain, nonatomic) UIColor* foregroundColor;
@property(retain, nonatomic) UIColor* backgroundColor;
@property(copy, nonatomic) NSString* name;
+(id)colorWithHexString:(id)hexString;
-(void)setNormalFontName:(id)name italicFontName:(id)name2 boldFontName:(id)name3 boldItalicFontName:(id)name4 size:(float)size;
-(void)setFontName:(id)name size:(float)size;
-(CTParagraphStyleRef)createParagraphStyleForString:(id)string textRectWidth:(float)width;
-(id)bestStyleForScope:(id)scope;
-(void)dealloc;
-(void)releaseFonts;
-(id)initWithThemeDictionary:(id)themeDictionary;
@end

