/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class ABDocumentLineTree, NSString, ABLineManager, NSMutableString;

@interface ABTextDocument : NSObject {
	NSMutableString* _completeText;
	ABDocumentLineTree* _lineTree;
	ABLineManager* _lineManager;
}
@property(assign, nonatomic) NSString* text;
-(void)logLineTree;
-(id)substringWithRange:(NSRange)range;
-(id)stringOfLineIncludingDelimiterAtIndex:(unsigned)index;
-(id)stringOfLineAtIndex:(unsigned)index;
-(id)stringOfLineIncludingDelimiter:(id)lineIncludingDelimiter;
-(id)stringOfLine:(id)line;
-(unsigned)textLength;
-(unsigned)lineCount;
-(unsigned)locationOfDocumentLine:(id)documentLine;
-(id)documentLineFromLocation:(unsigned)location;
-(unsigned)indexOfDocumentLine:(id)documentLine;
-(id)documentLineAtIndex:(unsigned)index;
-(unsigned short)characterAtIndex:(unsigned)index;
-(void)deleteCharactersInRange:(NSRange)range;
-(void)insertString:(id)string atIndex:(unsigned)index;
-(void)replaceCharactersInRange:(NSRange)range withString:(id)string;
-(void)dealloc;
-(id)init;
@end

