/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ABIntegerArrayBase.h"


@interface ABUnsignedIntegerArray : ABIntegerArrayBase {
}
-(void)removeValuesIdenticalToUnsignedIntegerValue:(unsigned)unsignedIntegerValue;
-(void)replaceValueAtIndex:(unsigned)index withUnsignedInteger:(unsigned)unsignedInteger;
-(void)insertUnsignedInteger:(unsigned)integer atIndex:(unsigned)index;
-(void)addUnsignedInteger:(unsigned)integer;
-(unsigned)unsignedIntegerAtIndex:(unsigned)index;
@end

