/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIControl.h>

@class NSTimer;

__attribute__((visibility("hidden")))
@interface ABUpDownControl : UIControl {
	BOOL _selected;
	BOOL _topHalfSelected;
	BOOL _touchNeedsDisplay;
	NSTimer* _arrowTimer;
	BOOL _timerFired;
	int maximumAllowedValue;
	int minimumAllowedValue;
	int value;
}
@property(assign, nonatomic) int value;
@property(assign, nonatomic) int minimumAllowedValue;
@property(assign, nonatomic) int maximumAllowedValue;
-(void)dealloc;
-(void)endTrackingWithTouch:(id)touch withEvent:(id)event;
-(BOOL)continueTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)cancelTrackingWithEvent:(id)event;
-(BOOL)beginTrackingWithTouch:(id)touch withEvent:(id)event;
-(void)stopTimer;
-(void)timerFired:(id)fired;
-(void)createArrowKeyTimer;
-(void)drawRect:(CGRect)rect;
-(void)processTouchUp;
@end

