/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol AddFileViewControllerDelegate <NSObject>
@optional
-(void)addFileViewController:(id)controller insertFileInformation:(id)information;
-(BOOL)addFileViewController:(id)controller insertNewFileInformation:(id)information;
@end

