/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSCoding.h"

@class DBQuota, NSString;

__attribute__((visibility("hidden")))
@interface DBAccountInfo : NSObject <NSCoding> {
	NSString* country;
	NSString* displayName;
	DBQuota* quota;
	NSString* userId;
	NSString* referralLink;
}
@property(readonly, assign, nonatomic) NSString* referralLink;
@property(readonly, assign, nonatomic) NSString* userId;
@property(readonly, assign, nonatomic) DBQuota* quota;
@property(readonly, assign, nonatomic) NSString* displayName;
@property(readonly, assign, nonatomic) NSString* country;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

