/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIViewController.h>
#import "UITextFieldDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "DBRestClientDelegate.h"

@class UITextField, UIView, UITableView, UIActivityIndicatorView, DBLoadingView, DBLoginController, DBRestClient, UITableViewCell;

__attribute__((visibility("hidden")))
@interface DBCreateAccountController : UIViewController <UITextFieldDelegate, DBRestClientDelegate, UITableViewDataSource, UITableViewDelegate> {
	BOOL hasCreatedAccount;
	DBLoginController* loginController;
	DBRestClient* restClient;
	UITableView* tableView;
	UIView* headerView;
	UITableViewCell* firstNameCell;
	UITextField* firstNameField;
	UITableViewCell* lastNameCell;
	UITextField* lastNameField;
	UITableViewCell* emailCell;
	UITextField* emailField;
	UITableViewCell* passwordCell;
	UITextField* passwordField;
	UIView* footerView;
	UIActivityIndicatorView* activityIndicator;
	DBLoadingView* loadingView;
}
@property(readonly, assign, nonatomic) DBRestClient* restClient;
@property(assign, nonatomic) DBLoginController* loginController;
-(void)errorWithTitle:(id)title message:(id)message;
-(void)updateActionButton;
-(void)setWorking:(BOOL)working;
-(void)restClient:(id)client loginFailedWithError:(id)error;
-(void)restClientDidLogin:(id)restClient;
-(void)restClient:(id)client createAccountFailedWithError:(id)error;
-(void)restClientCreatedAccount:(id)account;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)newCellWithLabel:(id)label textField:(id)field;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)didPressCreateAccount;
-(void)dealloc;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)releaseViews;
-(void)viewDidLoad;
@end

