/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIActivityIndicatorView, UIImageView;

__attribute__((visibility("hidden")))
@interface DBLoadingView : UIView {
	int orientation;
	UILabel* titleLabel;
	UIActivityIndicatorView* activityIndicator;
	UIImageView* imageView;
}
-(CGRect)beveledBoxFrame;
-(void)dismissAnimated:(BOOL)animated;
-(void)finishDismiss;
-(void)show;
-(void)setOrientation:(int)orientation;
-(void)setImage:(id)image;
-(void)dealloc;
-(void)layoutSubviews;
-(void)drawRect:(CGRect)rect;
-(id)initWithTitle:(id)title;
-(id)init;
@end

