/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIViewController.h>
#import "UITextFieldDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "DBRestClientDelegate.h"

@class UITextField, UIView, UITableView, UIActivityIndicatorView, DBLoadingView, DBRestClient, UIImageView, UITableViewCell;
@protocol DBLoginControllerDelegate;

__attribute__((visibility("hidden")))
@interface DBLoginController : UIViewController <UITextFieldDelegate, DBRestClientDelegate, UITableViewDataSource, UITableViewDelegate> {
	BOOL hasAppeared;
	id<DBLoginControllerDelegate> delegate;
	UITableView* tableView;
	UIImageView* descriptionLabel;
	UITableViewCell* emailCell;
	UITextField* emailField;
	UITableViewCell* passwordCell;
	UITextField* passwordField;
	UIView* footerView;
	DBLoadingView* loadingView;
	UIActivityIndicatorView* activityIndicator;
	DBRestClient* restClient;
}
@property(readonly, assign, nonatomic) DBRestClient* restClient;
@property(assign, nonatomic) id<DBLoginControllerDelegate> delegate;
-(void)updateActionButton;
-(void)errorWithTitle:(id)title message:(id)message;
-(void)setWorking:(BOOL)working;
-(void)restClient:(id)client loginFailedWithError:(id)error;
-(void)restClientDidLogin:(id)restClient;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)newCellWithTitle:(id)title textField:(id)field;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(void)didPressCancel;
-(void)didPressCreateAccount;
-(void)didPressLogin;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)presentFromController:(id)controller;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)releaseViews;
-(void)viewDidLoad;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
@end

