/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <Foundation/NSObject.h>

@class NSDate, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface DBMetadata : NSObject <NSCoding> {
	BOOL thumbnailExists;
	long long totalBytes;
	NSDate* lastModifiedDate;
	NSString* path;
	BOOL isDirectory;
	NSArray* contents;
	NSString* hash;
	NSString* humanReadableSize;
	NSString* root;
	NSString* icon;
	long long revision;
	BOOL isDeleted;
}
@property(readonly, assign, nonatomic) BOOL isDeleted;
@property(readonly, assign, nonatomic) long long revision;
@property(readonly, assign, nonatomic) NSString* icon;
@property(readonly, assign, nonatomic) NSString* root;
@property(readonly, assign, nonatomic) NSString* humanReadableSize;
@property(readonly, assign, nonatomic) NSString* hash;
@property(readonly, assign, nonatomic) NSArray* contents;
@property(readonly, assign, nonatomic) BOOL isDirectory;
@property(readonly, assign, nonatomic) NSString* path;
@property(readonly, assign, nonatomic) NSDate* lastModifiedDate;
@property(readonly, assign, nonatomic) long long totalBytes;
@property(readonly, assign, nonatomic) BOOL thumbnailExists;
+(id)dateFormatter;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(void)dealloc;
-(id)initWithDictionary:(id)dictionary;
@end

