/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSError, NSString, NSFileHandle, NSHTTPURLResponse, NSData, NSURLConnection, NSMutableData, NSDictionary, NSURLRequest;

__attribute__((visibility("hidden")))
@interface DBRequest : NSObject {
	NSURLRequest* request;
	id target;
	SEL selector;
	NSURLConnection* urlConnection;
	NSFileHandle* fileHandle;
	SEL failureSelector;
	SEL downloadProgressSelector;
	SEL uploadProgressSelector;
	NSString* resultFilename;
	NSString* tempFilename;
	NSDictionary* userInfo;
	NSHTTPURLResponse* response;
	int bytesDownloaded;
	float downloadProgress;
	float uploadProgress;
	NSMutableData* resultData;
	NSError* error;
}
@property(readonly, assign, nonatomic) NSError* error;
@property(readonly, assign, nonatomic) NSObject* resultJSON;
@property(readonly, assign, nonatomic) NSString* resultString;
@property(readonly, assign, nonatomic) NSData* resultData;
@property(readonly, assign, nonatomic) float uploadProgress;
@property(readonly, assign, nonatomic) float downloadProgress;
@property(readonly, assign, nonatomic) int statusCode;
@property(readonly, assign, nonatomic) NSHTTPURLResponse* response;
@property(readonly, assign, nonatomic) NSURLRequest* request;
@property(retain, nonatomic) NSDictionary* userInfo;
@property(retain, nonatomic) NSString* resultFilename;
@property(assign, nonatomic) SEL uploadProgressSelector;
@property(assign, nonatomic) SEL downloadProgressSelector;
@property(assign, nonatomic) SEL failureSelector;
+(void)setNetworkRequestDelegate:(id)delegate;
-(void)connection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)cancel;
-(void)dealloc;
-(id)initWithURLRequest:(id)urlrequest andInformTarget:(id)target selector:(SEL)selector;
@end

