/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableSet, NSString, DBSession, NSMutableDictionary;
@protocol DBRestClientDelegate;

__attribute__((visibility("hidden")))
@interface DBRestClient : NSObject {
	DBSession* session;
	NSString* root;
	NSMutableSet* requests;
	NSMutableDictionary* loadRequests;
	id<DBRestClientDelegate> delegate;
}
@property(assign, nonatomic) id<DBRestClientDelegate> delegate;
+(id)escapePath:(id)path;
-(void)checkForAuthenticationFailure:(id)authenticationFailure;
-(id)requestWithProtocol:(id)protocol host:(id)host path:(id)path parameters:(id)parameters method:(id)method;
-(id)requestWithProtocol:(id)protocol host:(id)host path:(id)path parameters:(id)parameters;
-(void)requestDidCreateAccount:(id)request;
-(void)createAccount:(id)account password:(id)password firstName:(id)name lastName:(id)name4;
-(void)requestDidLoadAccountInfo:(id)request;
-(void)loadAccountInfo;
-(void)requestDidCreateDirectory:(id)request;
-(void)createFolder:(id)folder;
-(void)requestDidDeletePath:(id)request;
-(void)deletePath:(id)path;
-(void)requestDidCopyPath:(id)request;
-(void)copyFrom:(id)from toPath:(id)path;
-(void)requestDidMovePath:(id)request;
-(void)moveFrom:(id)from toPath:(id)path;
-(void)requestDidUploadFile:(id)request;
-(void)requestUploadProgress:(id)progress;
-(void)uploadFile:(id)file toPath:(id)path fromPath:(id)path3;
-(void)requestDidLoadThumbnail:(id)request;
-(void)loadThumbnail:(id)thumbnail ofSize:(id)size intoPath:(id)path;
-(void)requestDidLoadFile:(id)request;
-(void)restClient:(id)client loadedFile:(id)file contentType:(id)type eTag:(id)tag;
-(void)requestLoadProgress:(id)progress;
-(void)cancelFileLoad:(id)load;
-(void)loadFile:(id)file intoPath:(id)path;
-(void)didParseMetadata:(id)metadata;
-(void)parseMetadataWithRequest:(id)request;
-(void)requestDidLoadMetadata:(id)request;
-(void)loadMetadata:(id)metadata;
-(void)loadMetadata:(id)metadata withHash:(id)hash;
-(void)requestDidLogin:(id)request;
-(void)loginWithEmail:(id)email password:(id)password;
-(void)dealloc;
-(id)initWithSession:(id)session root:(id)root;
-(id)initWithSession:(id)session;
@end

