/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class DropboxConnection, MPOAuthCredentialConcreteStore;
@protocol DBSessionDelegate;

__attribute__((visibility("hidden")))
@interface DBSession : NSObject {
	MPOAuthCredentialConcreteStore* credentialStore;
	id<DBSessionDelegate> delegate;
	DropboxConnection* dropboxConnection;
}
@property(retain, nonatomic) DropboxConnection* dropboxConnection;
@property(assign, nonatomic) id<DBSessionDelegate> delegate;
@property(readonly, assign, nonatomic) MPOAuthCredentialConcreteStore* credentialStore;
+(void)setSharedSession:(id)session;
+(id)sharedSession;
-(void)clearSavedCredentials;
-(void)saveCredentials:(id)credentials;
-(id)savedCredentials;
-(void)unlink;
-(BOOL)isLinked;
-(void)updateAccessToken:(id)token accessTokenSecret:(id)secret;
-(void)dealloc;
-(id)initWithConsumerKey:(id)consumerKey consumerSecret:(id)secret dropboxConnection:(id)connection;
@end

