/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSProxy.h>

@class NSInvocation;

__attribute__((visibility("hidden")))
@interface DDInvocationGrabber : NSProxy {
	id _target;
	NSInvocation* _invocation;
	BOOL _forwardInvokesOnMainThread;
	BOOL _waitUntilDone;
}
+(id)invocationGrabber;
-(void)forwardInvocation:(id)invocation;
-(id)methodSignatureForSelector:(SEL)selector;
-(void)setWaitUntilDone:(BOOL)done;
-(BOOL)waitUntilDone;
-(void)setForwardInvokesOnMainThread:(BOOL)thread;
-(BOOL)forwardInvokesOnMainThread;
-(void)setInvocation:(id)invocation;
-(id)invocation;
-(void)setTarget:(id)target;
-(id)target;
-(void)dealloc;
-(id)init;
-(id)prepareWithInvocationTarget:(id)invocationTarget;
@end

