/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"
#import "SelectStringEncodingViewControllerDelegate.h"
#import "SCTableViewModelDataSource.h"
#import "SelectLineEndingTypeViewControllerDelegate.h"
#import "SCTableViewModelDelegate.h"

@class FileInformation;

__attribute__((visibility("hidden")))
@interface DocumentSettingsViewController : SCTableViewController <SCTableViewModelDelegate, SCTableViewModelDataSource, SelectStringEncodingViewControllerDelegate, SelectLineEndingTypeViewControllerDelegate> {
	FileInformation* fileInfo;
}
@property(retain, nonatomic) FileInformation* fileInfo;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)refreshWithFileInformation:(id)fileInformation;
-(void)selectLineEndingTypeViewController:(id)controller didSelectLineEndingType:(int)type;
-(void)selectStringEncodingViewController:(id)controller didSelectStringEncoding:(unsigned)encoding;
-(void)tableViewModel:(id)model didSelectRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)initWithStyle:(int)style;
@end

