/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RemoteConnection.h"

@class DBSession, NSOperationQueue, NSDictionary;

__attribute__((visibility("hidden")))
@interface DropboxConnection : RemoteConnection {
	NSOperationQueue* queue;
	DBSession* session;
	NSDictionary* dropboxCredentials;
}
@property(retain, nonatomic) NSDictionary* dropboxCredentials;
-(id)configurationViewControllerWithMode:(int)mode andDelegate:(id)delegate;
-(id)titleForConnectionList;
-(id)navigationItemTitleForPath:(id)path;
-(void)renameFile:(id)file newFileName:(id)name withDelegate:(id)delegate;
-(void)deleteFile:(id)file withDelegate:(id)delegate;
-(void)checkIfFileExistsAt:(id)at withDelegate:(id)delegate userData:(id)data;
-(void)createDirectory:(id)directory withDelegate:(id)delegate userData:(id)data;
-(void)uploadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)downloadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)requestRemoteFileInformationArrayForSubdirectory:(id)subdirectory withDelegate:(id)delegate;
-(id)cancelError;
-(id)ensureCorrectDropboxPath:(id)path;
-(void)cancelAllRequests;
-(void)loadConfigFromDictionary:(id)dictionary;
-(id)configDictionary;
-(int)remoteConnectionType;
-(id)session;
-(void)dealloc;
-(id)init;
@end

