/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DBRestClientDelegate.h"
#import <Foundation/NSObject.h>

@class NSString, NSOperation, RemoteFileInformation, RemoteConnection, FileInformation;
@protocol RemoteConnectionDelegate;

__attribute__((visibility("hidden")))
@interface DropboxConnectionRestClientDelegate : NSObject <DBRestClientDelegate> {
	RemoteConnection* connection;
	NSObject<RemoteConnectionDelegate>* delegate;
	BOOL delegateMethodCalled;
	RemoteFileInformation* remoteFileInfo;
	FileInformation* fileInfo;
	NSOperation* operation;
	int requestType;
	NSString* remotePath;
	id userData;
}
@property(retain, nonatomic) NSString* remotePath;
@property(assign, nonatomic) id userData;
@property(retain, nonatomic) RemoteConnection* connection;
@property(readonly, assign, nonatomic) BOOL delegateMethodCalled;
@property(retain, nonatomic) NSOperation* operation;
@property(retain, nonatomic) FileInformation* fileInfo;
@property(retain, nonatomic) RemoteFileInformation* remoteFileInfo;
-(void)restClient:(id)client createAccountFailedWithError:(id)error;
-(void)restClientCreatedAccount:(id)account;
-(void)restClient:(id)client movePathFailedWithError:(id)error;
-(void)restClient:(id)client movedPath:(id)path toPath:(id)path3;
-(void)restClient:(id)client copyPathFailedWithError:(id)error;
-(void)restClient:(id)client copiedPath:(id)path toPath:(id)path3;
-(void)restClient:(id)client deletePathFailedWithError:(id)error;
-(void)restClient:(id)client deletedPath:(id)path;
-(void)restClient:(id)client createFolderFailedWithError:(id)error;
-(void)restClient:(id)client createdFolder:(id)folder;
-(void)restClient:(id)client uploadFileFailedWithError:(id)error;
-(void)restClient:(id)client uploadProgress:(float)progress forFile:(id)file from:(id)from;
-(void)restClient:(id)client uploadedFile:(id)file from:(id)from;
-(void)restClient:(id)client loadThumbnailFailedWithError:(id)error;
-(void)restClient:(id)client loadedThumbnail:(id)thumbnail;
-(void)restClient:(id)client loadFileFailedWithError:(id)error;
-(void)restClient:(id)client loadProgress:(float)progress forFile:(id)file;
-(void)restClient:(id)client loadedFile:(id)file contentType:(id)type;
-(void)restClient:(id)client loadAccountInfoFailedWithError:(id)error;
-(void)restClient:(id)client loadedAccountInfo:(id)info;
-(void)restClient:(id)client loadMetadataFailedWithError:(id)error;
-(void)restClient:(id)client loadedMetadata:(id)metadata;
-(BOOL)waitUntilDelegateMethodCalled;
-(void)dealloc;
-(id)initWithRemoteConnection:(id)remoteConnection delegate:(id)delegate operation:(id)operation requestType:(int)type;
@end

