/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"
#import "DBLoginControllerDelegate.h"
#import "SCTableViewModelDelegate.h"

@class DBSession, SCTableViewCell, DropboxConnection;
@protocol RemoteConnectionConfigurationDelegate;

__attribute__((visibility("hidden")))
@interface DropboxConfigurationViewController : SCTableViewController <SCTableViewModelDelegate, DBLoginControllerDelegate> {
	DropboxConnection* connection;
	id<RemoteConnectionConfigurationDelegate> remoteConnectionConfigurationDelegate;
	int configurationMode;
	DBSession* session;
	SCTableViewCell* linkCell;
}
@property(retain, nonatomic) DBSession* session;
@property(retain, nonatomic) DropboxConnection* connection;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)cancelButtonAction;
-(void)doneButtonAction;
-(void)viewWillAppear:(BOOL)view;
-(void)tableViewModel:(id)model didSelectRowAtIndexPath:(id)indexPath;
-(void)loginControllerDidCancel:(id)loginController;
-(void)loginControllerDidLogin:(id)loginController;
-(BOOL)tableViewModel:(id)model valueIsValidForRowAtIndexPath:(id)indexPath;
-(id)initWithDropboxConnection:(id)dropboxConnection session:(id)session mode:(int)mode delegate:(id)delegate;
@end

