/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "Textastic-Structs.h"
#import <UIKit/UIViewController.h>
#import "MFMailComposeViewControllerDelegate.h"
#import "ABCodeEditorContentViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "UIActionSheetDelegate.h"

@class DocumentSettingsViewController, SearchViewController, UISegmentedControl, UIView, ABCodeEditorAccessoryView, SymbolListViewController, ABCodeEditorCursorControl, RecentFilesViewController, UIButton, UIBarButtonItem, UIActionSheet, NSURL, ABCodeEditorView, FileInformation;

__attribute__((visibility("hidden")))
@interface EditorViewController : UIViewController <ABCodeEditorContentViewDelegate, UIActionSheetDelegate, MFMailComposeViewControllerDelegate, UIDocumentInteractionControllerDelegate, UIAlertViewDelegate, UIWebViewDelegate> {
	ABCodeEditorView* editor;
	UIView* containerView;
	UIButton* fileNameButton;
	UIActionSheet* fileActionSheet;
	UIActionSheet* remoteConnectionActionSheet;
	UIBarButtonItem* actionButton;
	UIBarButtonItem* documentSettingsButton;
	UIBarButtonItem* searchButton;
	UISegmentedControl* undoSegmentedControl;
	UIBarButtonItem* undoButton;
	UIBarButtonItem* toggleSidebarButton;
	UIBarButtonItem* previewButton;
	UIBarButtonItem* symbolListButton;
	UIBarButtonItem* fileNameBarButtonItem;
	UIBarButtonItem* doneButton;
	UIBarButtonItem* backButton;
	DocumentSettingsViewController* documentSettingsViewController;
	SearchViewController* searchViewController;
	UISegmentedControl* webPreviewSegmentedControl;
	NSURL* url;
	SymbolListViewController* symbolListViewController;
	RecentFilesViewController* recentFilesViewController;
	ABCodeEditorAccessoryView* accessoryView;
	ABCodeEditorCursorControl* _cursorControl;
	BOOL initialized;
	BOOL keyboardShown;
	BOOL opening;
	FileInformation* currentFile;
	BOOL hardwareKeyboard;
	BOOL keyboardAdditionalKeys;
	BOOL hidingAdditionalKeys;
	BOOL webPreviewWasFirstResponder;
	BOOL createGettingStartedFileOnStartup;
	BOOL overrideOpenFileChecksBinary;
	BOOL overrideOpenFileChecksSize;
	FileInformation* openFileCheckFileInformation;
	int remoteConnectionCount;
	BOOL remoteConnectionActionSheetUpload;
}
@property(readonly, assign, nonatomic) SearchViewController* searchViewController;
@property(retain, nonatomic) FileInformation* openFileCheckFileInformation;
@property(assign, nonatomic) BOOL createGettingStartedFileOnStartup;
@property(assign, nonatomic) BOOL keyboardAdditionalKeys;
@property(retain, nonatomic) UIBarButtonItem* previewButton;
@property(retain, nonatomic) UIBarButtonItem* symbolListButton;
@property(retain, nonatomic) UIBarButtonItem* searchButton;
@property(retain, nonatomic) UIBarButtonItem* documentSettingsButton;
@property(readonly, assign, nonatomic) FileInformation* currentFile;
@property(retain, nonatomic) UIBarButtonItem* actionButton;
@property(retain, nonatomic) UIView* containerView;
@property(retain, nonatomic) ABCodeEditorView* editor;
-(void)dealloc;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)codeEditorContentViewDidResignFirstResponder:(id)codeEditorContentView;
-(void)codeEditorContentViewDidBecomeFirstResponder:(id)codeEditorContentView;
-(void)codeEditorContentViewSelectionDidChange:(id)codeEditorContentViewSelection;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)setSyntaxNode:(id)node;
-(void)syntaxButtonAction:(id)action;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)showKeyboard:(BOOL)keyboard containerFrame:(CGRect)frame keyboardNotification:(id)notification;
-(id)imageWithColor:(id)color;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)previewAction:(id)action;
-(void)settingsAction:(id)action;
-(void)viewDidLoad;
-(void)undoAction:(id)action;
-(void)doneButtonAction:(id)action;
-(void)searchAction:(id)action;
-(void)fileNameButtonAction:(id)action;
-(void)symbolListAction:(id)action;
-(void)documentSettingsAction:(id)action;
-(void)actionButtonAction:(id)action;
-(void)backButtonAction:(id)action;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)transferFileUpload:(BOOL)upload withLinkedConnection:(id)linkedConnection;
-(id)documentInteractionControllerViewControllerForPreview:(id)preview;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(void)openFile:(id)file;
-(id)syntaxNodeForFile:(id)file;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)closeCurrentFile;
-(void)refreshUndoButtonState;
-(void)finishOpening;
-(void)fadeOutAnimationDidStop:(id)fadeOutAnimation finished:(id)finished context:(void*)context;
-(void)saveCurrentFile;
-(void)setFileNameButtonFrameWithInterfaceOrientation:(int)interfaceOrientation;
-(void)openLastFile;
-(void)refreshAccessoryView;
-(void)saveSettings;
-(BOOL)currentFileIsMarkdown;
-(void)loadSettings;
@end

