/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface FileTableViewCell : UITableViewCell {
	UIImageView* markedImageView;
	BOOL marked;
	BOOL shouldShowMark;
}
@property(assign, nonatomic) BOOL marked;
-(void)dealloc;
-(void)layoutSubviews;
-(void)didTransitionToState:(unsigned)state;
-(void)willTransitionToState:(unsigned)state;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(void)updateMarkedState;
@end

