/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import <UIKit/UIViewController.h>
#import "UINavigationControllerDelegate.h"
#import "Textastic-Structs.h"

@class UINavigationController, UISegmentedControl, FileTransferConnectionsViewController, LocalDirectoryViewController, UIToolbar, UIScrollView, UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface FileTransferViewController : UIViewController <UINavigationControllerDelegate, UIScrollViewDelegate> {
	UIToolbar* topToolbar;
	UINavigationController* leftNavigationController;
	UINavigationController* rightNavigationController;
	UISegmentedControl* _localRemoteSegmentedControl;
	UIBarButtonItem* _localRemoteItem;
	UIScrollView* _scrollView;
	FileTransferConnectionsViewController* connectionsViewController;
	LocalDirectoryViewController* localFilesViewController;
}
@property(readonly, assign, nonatomic) FileTransferConnectionsViewController* connectionsViewController;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)saveConnections;
-(void)refreshRemoteFileList;
-(void)refreshLocalFileList;
-(id)currentRemoteConnection;
-(id)currentRemotePath;
-(id)currentLocalPath;
-(id)currentRemoteDirectoryViewController;
-(void)switchToLocalPath:(id)localPath;
-(id)currentLocalDirectoryViewController;
-(void)viewDidLoad;
-(void)localRemoteAction:(id)action;
-(void)navigationController:(id)controller didShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)backButtonAction:(id)action;
-(id)flexibleSpace;
-(void)layoutViews;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)layoutLocalRemoteAnimated:(BOOL)animated;
-(id)initWithNibName:(id)nibName bundle:(id)bundle;
@end

