/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RemoteConnectionConfigurationDelegate.h"
#import <UIKit/UITableViewController.h>
#import "UIActionSheetDelegate.h"

@class UIActionSheet, NSMutableArray;

__attribute__((visibility("hidden")))
@interface FileTransferConnectionsViewController : UITableViewController <RemoteConnectionConfigurationDelegate, UIActionSheetDelegate> {
	NSMutableArray* fileTransferConnections;
	UIActionSheet* addActionSheet;
}
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)remoteConnection:(id)connection cancelledWithMode:(int)mode;
-(void)remoteConnection:(id)connection savedWithMode:(int)mode;
-(void)addConnection:(id)connection;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(id)remoteConnectionWithUUID:(id)uuid;
-(unsigned)connectionCount;
-(void)saveConnections;
-(void)loadConnections;
-(void)viewDidLoad;
-(void)updateLeftButton;
@end

