/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FileTransferConnection : NSObject {
	NSString* title;
	int connectionType;
}
@property(assign, nonatomic) int connectionType;
@property(copy, nonatomic) NSString* title;
@end

