/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "AddFileViewControllerDelegate.h"
#import "RenameFileViewControllerDelegate.h"
#import "SelectDirectoryViewControllerDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "SelectStringEncodingViewControllerDelegate.h"
#import "MBProgressHUDDelegate.h"
#import "Textastic-Structs.h"
#import <UIKit/UITableViewController.h>
#import "SSZipArchiveDelegate.h"
#import "MFMailComposeViewControllerDelegate.h"

@class EditorViewController, UIDocumentInteractionController, UIButton, MBProgressHUD, UIBarButtonItem, NSMutableArray, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface FileTableViewController : UITableViewController <UIAlertViewDelegate, AddFileViewControllerDelegate, RenameFileViewControllerDelegate, SelectDirectoryViewControllerDelegate, UIDocumentInteractionControllerDelegate, SelectStringEncodingViewControllerDelegate, MBProgressHUDDelegate, SSZipArchiveDelegate, MFMailComposeViewControllerDelegate> {
	EditorViewController* editorViewController;
	NSString* path;
	NSMutableArray* fileInformationArray;
	UIButton* deleteButton;
	UIButton* moveButton;
	UIButton* zipButton;
	NSArray* savedToolbarItems;
	BOOL editingRow;
	UIBarButtonItem* webdavButton;
	UIBarButtonItem* helpButton;
	unsigned rowForLongPress;
	unsigned rowForUnzip;
	BOOL deletionConfirmed;
	BOOL webDAVstarted;
	MBProgressHUD* _hud;
	unsigned long long _zipTotalSize;
	UIDocumentInteractionController* _interactionController;
}
@property(readonly, assign, nonatomic) NSString* path;
@property(retain, nonatomic) EditorViewController* editorViewController;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(void)openHierarchyForPath:(id)path;
-(void)openHierarchyForFile:(id)file;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(BOOL)copyFile:(id)file newFileName:(id)name;
-(BOOL)renameFile:(id)file newFileName:(id)name;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)longPress:(id)press;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(id)makeRenameButton:(BOOL)button;
-(void)renameButtonTapped:(id)tapped withEvent:(id)event;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)listIsEmpty;
-(BOOL)listIsEmptyOrGettingStarted;
-(void)addFileViewController:(id)controller insertFileInformation:(id)information;
-(void)refreshFileList;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)selectCurrentFileAnimated:(BOOL)animated;
-(void)viewWillAppear:(BOOL)view;
-(void)helpAction:(id)action;
-(void)remoteConnectionAction:(id)action;
-(void)selectStringEncodingViewController:(id)controller didSelectStringEncoding:(unsigned)encoding;
-(void)documentInteractionControllerDidEndPreview:(id)documentInteractionController;
-(id)documentInteractionControllerViewForPreview:(id)preview;
-(id)documentInteractionControllerViewControllerForPreview:(id)preview;
-(void)documentInteractionControllerDidDismissOpenInMenu:(id)documentInteractionController;
-(void)settingsAction:(id)action;
-(void)refreshAction:(id)action;
-(void)webdavAction:(id)action;
-(void)zipAction:(id)action;
-(void)flashFileWithFilePath:(id)filePath;
-(void)moveAction:(id)action;
-(void)selectDirectoryViewController:(id)controller didSelectFolder:(id)folder;
-(void)deleteAction:(id)action;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)zipArchiveDidUnzipFileAtIndex:(int)zipArchive totalFiles:(int)files archivePath:(id)path fileInfo:(unz_file_info_s)info;
-(void)hideHUD;
-(void)showHUDWithLabelText:(id)labelText;
-(void)hudWasHidden:(id)hidden;
-(void)addAction:(id)action;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)updateEditButtons;
-(void)webdavServerStopped;
-(void)webdavServerStarted;
-(void)viewDidLoad;
-(void)refreshToolbarItems;
-(id)initWithPathOrNil:(id)pathOrNil;
@end

