/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FILinkedConnection : NSObject {
	NSString* uuid;
	NSString* remotePath;
}
@property(copy, nonatomic) NSString* remotePath;
@property(copy, nonatomic) NSString* uuid;
+(id)linkedConnectionWithDictionary:(id)dictionary;
+(id)linkedConnectionWithUUID:(id)uuid remotePath:(id)path;
-(id)dictionary;
-(void)dealloc;
-(id)initWithUUID:(id)uuid remotePath:(id)path;
@end

