/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class FMDatabase, NSString;

__attribute__((visibility("hidden")))
@interface FMDatabaseQueue : NSObject {
	NSString* _path;
	dispatch_queue_s* _queue;
	FMDatabase* _db;
}
@property(retain) NSString* path;
+(id)databaseQueueWithPath:(id)path;
-(id)inSavePoint:(id)savePoint;
-(void)inTransaction:(id)transaction;
-(void)inDeferredTransaction:(id)deferredTransaction;
-(void)beginTransaction:(BOOL)transaction withBlock:(id)block;
-(void)inDatabase:(id)database;
-(id)database;
-(void)close;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

