/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface FMDatabasePool : NSObject {
	NSString* _path;
	dispatch_queue_s* _lockQueue;
	NSMutableArray* _databaseInPool;
	NSMutableArray* _databaseOutPool;
	id _delegate;
	unsigned _maximumNumberOfDatabasesToCreate;
}
@property(assign) unsigned maximumNumberOfDatabasesToCreate;
@property(assign) id delegate;
@property(retain) NSString* path;
+(id)databasePoolWithPath:(id)path;
-(id)inSavePoint:(id)savePoint;
-(void)inTransaction:(id)transaction;
-(void)inDeferredTransaction:(id)deferredTransaction;
-(void)beginTransaction:(BOOL)transaction withBlock:(id)block;
-(void)inDatabase:(id)database;
-(void)releaseAllDatabases;
-(unsigned)countOfOpenDatabases;
-(unsigned)countOfCheckedOutDatabases;
-(unsigned)countOfCheckedInDatabases;
-(id)db;
-(void)pushDatabaseBackInPool:(id)pool;
-(void)executeLocked:(id)locked;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

