/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface FMStatement : NSObject {
	sqlite3_stmt* _statement;
	NSString* _query;
	long _useCount;
}
@property(assign) sqlite3_stmt* statement;
@property(retain) NSString* query;
@property(assign) long useCount;
-(id)description;
-(void)reset;
-(void)close;
-(void)dealloc;
-(void)finalize;
@end

