/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSXMLParserDelegate.h"

@class NSURLConnection, NSMutableData, NSURLRequest, NSMutableString, NSURL, NSError, RemoteFileInformation, NSOperation, NSFileHandle, NSInputStream, NSMutableArray, NSString, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface FMWebDAVRequest : NSObject <NSXMLParserDelegate> {
	NSURLConnection* _connection;
	NSMutableData* _responseData;
	NSURLRequest* _request;
	NSMutableString* _xmlChars;
	NSMutableDictionary* _xmlBucket;
	RemoteFileInformation* _remoteFileInformation;
	NSString* _remoteFileInformationBasePath;
	NSMutableArray* _directoryBucket;
	NSURL* _url;
	id _delegate;
	id _contextInfo;
	SEL _endSelector;
	unsigned _parseState;
	unsigned _uriLength;
	unsigned _depth;
	int _responseStatusCode;
	BOOL _synchronous;
	BOOL _rlSynchronous;
	NSError* _error;
	NSString* _username;
	NSString* _password;
	BOOL _verifySSLCertificate;
	NSOperation* _operation;
	NSString* _localFileName;
	NSFileHandle* _fileHandle;
	NSInputStream* _fileStream;
	unsigned long long _bytesDownloaded;
	unsigned long long _contentLength;
	id _finishBlock;
	void* _userData;
}
@property(readonly, assign) NSString* localFileName;
@property(assign) BOOL verifySSLCertificate;
@property(assign) void* userData;
@property(retain) NSString* password;
@property(retain) NSString* username;
@property(retain) NSError* error;
@property(assign) int responseStatusCode;
@property(assign) SEL endSelector;
@property(retain) id contextInfo;
@property(assign) id delegate;
@property(retain) NSURL* url;
@property(retain) NSMutableData* responseData;
@property(retain) NSURLConnection* connection;
+(id)parseDateString:(id)string;
+(id)requestToURL:(id)url delegate:(id)delegate endSelector:(SEL)selector contextInfo:(id)info;
+(id)requestToURL:(id)url delegate:(id)delegate;
+(id)requestToURL:(id)url;
-(void)parser:(id)parser foundCharacters:(id)characters;
-(void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
-(void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(BOOL)connection:(id)connection canAuthenticateAgainstProtectionSpace:(id)space;
-(void)connection:(id)connection didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write;
-(void)connection:(id)connection didReceiveData:(id)data;
-(id)responseString;
-(id)remoteFileInformationArrayWithBasePath:(id)basePath;
-(id)directoryListingWithAttributes;
-(id)directoryListing;
-(id)fetchDirectoryListingWithDepth:(unsigned)depth extraToPropfind:(id)propfind;
-(id)fetchDirectoryListingWithDepth:(unsigned)depth;
-(id)fetchDirectoryListing;
-(id)propfind;
-(id)head;
-(id)moveToDestinationURL:(id)destinationURL;
-(id)copyToDestinationURL:(id)destinationURL;
-(id)getIntoFile:(id)file;
-(id)get;
-(id)putFile:(id)file;
-(id)putData:(id)data;
-(id)delete;
-(id)createDirectory;
-(void)sendRequest:(id)request;
-(id)withFinishBlock:(id)finishBlock;
-(id)rlsynchronous:(id)rlsynchronous;
-(id)synchronous;
-(void)dealloc;
-(id)init;
@end

