/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>
#import "MFMailComposeViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"

@class UIActionSheet;

__attribute__((visibility("hidden")))
@interface HelpViewController : UITableViewController <MFMailComposeViewControllerDelegate, UIActionSheetDelegate> {
	UIActionSheet* _rateSheet;
}
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)mailComposeController:(id)controller didFinishWithResult:(int)result error:(id)error;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)appVersion;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)doneAction:(id)action;
-(void)viewDidLoad;
@end

