/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSFormatter.h>
#import "Textastic-Structs.h"

@class NSTimeZone;

__attribute__((visibility("hidden")))
@interface ISO8601DateFormatter : NSFormatter {
	NSTimeZone* defaultTimeZone;
	unsigned format;
	unsigned short timeSeparator;
	BOOL includeTime;
	BOOL parsesStrictly;
}
@property(assign) unsigned short timeSeparator;
@property(assign) BOOL includeTime;
@property(assign) unsigned format;
@property(assign) BOOL parsesStrictly;
@property(retain) NSTimeZone* defaultTimeZone;
-(id)weekDateStringForDate:(id)date timeZone:(id)zone;
-(id)stringForObjectValue:(id)objectValue;
-(id)stringFromDate:(id)date formatString:(id)string timeZone:(id)zone;
-(id)stringFromDate:(id)date timeZone:(id)zone;
-(id)stringFromDate:(id)date;
-(id)replaceColonsInString:(id)string withTimeSeparator:(unsigned short)timeSeparator;
-(BOOL)getObjectValue:(id*)value forString:(id)string errorDescription:(id*)description;
-(id)dateFromString:(id)string timeZone:(out id*)zone range:(out NSRange*)range;
-(id)dateFromString:(id)string timeZone:(out id*)zone;
-(id)dateFromString:(id)string;
-(id)dateComponentsFromString:(id)string timeZone:(out id*)zone range:(out NSRange*)range;
-(id)dateComponentsFromString:(id)string timeZone:(out id*)zone;
-(id)dateComponentsFromString:(id)string;
-(void)dealloc;
-(id)init;
@end

