/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSEnumerator.h>


__attribute__((visibility("hidden")))
@interface JKDictionaryEnumerator : NSEnumerator {
	id collection;
	unsigned nextObject;
}
-(id)nextObject;
-(id)allObjects;
-(void)dealloc;
-(id)initWithJKDictionary:(id)jkdictionary;
@end

