/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UIActionSheetDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import <UIKit/UITableViewController.h>
#import "AddFileViewControllerDelegate.h"
#import "RenameFileViewControllerDelegate.h"

@class NSMutableArray, NSString, UIActionSheet, UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface LocalDirectoryViewController : UITableViewController <AddFileViewControllerDelegate, UIActionSheetDelegate, RenameFileViewControllerDelegate, UIDocumentInteractionControllerDelegate> {
	NSString* path;
	NSMutableArray* fileInformationArray;
	BOOL deletionConfirmed;
	BOOL editingRow;
	int rowForRenameCopy;
	UIBarButtonItem* uploadButton;
	UIActionSheet* fileActionSheet;
	BOOL preventRefresh;
}
@property(readonly, assign, nonatomic) NSString* path;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(void)openHierarchyForPath:(id)path;
-(void)openHierarchyForFile:(id)file;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(BOOL)copyFile:(id)file newFileName:(id)name;
-(BOOL)renameFile:(id)file newFileName:(id)name;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)contentViewLongPress:(id)press;
-(void)contentViewTap:(id)tap;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)makeRenameButton:(BOOL)button;
-(void)renameButtonTapped:(id)tapped withEvent:(id)event;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)addFileViewController:(id)controller insertFileInformation:(id)information;
-(void)refreshFileList;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)refreshAction:(id)action;
-(void)deleteAction:(id)action;
-(void)uploadAction:(id)action;
-(void)uploadSelectedFilesToDirectory:(id)directory;
-(void)selectAll:(BOOL)all;
-(void)fileActionAction:(id)action;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)documentInteractionControllerDidEndPreview:(id)documentInteractionController;
-(id)documentInteractionControllerViewForPreview:(id)preview;
-(id)documentInteractionControllerViewControllerForPreview:(id)preview;
-(void)addAction:(id)action;
-(BOOL)dismissFileActionSheet;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)updateButtons;
-(void)viewDidLoad;
-(void)refreshToolbarItems;
-(id)fixedSpaceWithWidth:(float)width;
-(id)flexibleSpace;
-(id)initWithPathOrNil:(id)pathOrNil;
@end

