/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, NSTimer, NSDate, UIFont, NSString;
@protocol MBProgressHUDDelegate;

__attribute__((visibility("hidden")))
@interface MBProgressHUD : UIView {
	BOOL useAnimation;
	SEL methodForExecution;
	id targetForExecution;
	id objectForExecution;
	UILabel* label;
	UILabel* detailsLabel;
	BOOL isFinished;
	CGAffineTransform rotationTransform;
	int animationType;
	id<MBProgressHUDDelegate> delegate;
	float opacity;
	UIFont* labelFont;
	UIFont* detailsLabelFont;
	UIView* indicator;
	float xOffset;
	float yOffset;
	CGSize minSize;
	BOOL square;
	float margin;
	BOOL dimBackground;
	float graceTime;
	float minShowTime;
	NSTimer* graceTimer;
	NSTimer* minShowTimer;
	BOOL taskInProgress;
	BOOL removeFromSuperViewOnHide;
	UIView* customView;
	NSDate* showStarted;
	int mode;
	NSString* labelText;
	NSString* detailsLabelText;
	float progress;
	CGSize size;
}
@property(assign) CGSize size;
@property(retain) NSDate* showStarted;
@property(retain) NSTimer* minShowTimer;
@property(retain) NSTimer* graceTimer;
@property(retain) UIView* indicator;
@property(assign, getter=isSquare) BOOL square;
@property(assign) CGSize minSize;
@property(assign) float progress;
@property(retain) UIFont* detailsLabelFont;
@property(retain) UIFont* labelFont;
@property(assign) BOOL removeFromSuperViewOnHide;
@property(assign) BOOL taskInProgress;
@property(assign) float minShowTime;
@property(assign) float graceTime;
@property(assign) BOOL dimBackground;
@property(assign) float margin;
@property(assign) float yOffset;
@property(assign) float xOffset;
@property(assign) float opacity;
@property(copy) NSString* detailsLabelText;
@property(copy) NSString* labelText;
@property(assign) id<MBProgressHUDDelegate> delegate;
@property(retain) UIView* customView;
@property(assign) int animationType;
@property(assign) int mode;
+(id)allHUDsForView:(id)view;
+(id)HUDForView:(id)view;
+(unsigned)hideAllHUDsForView:(id)view animated:(BOOL)animated;
+(BOOL)hideHUDForView:(id)view animated:(BOOL)animated;
+(id)showHUDAddedTo:(id)to animated:(BOOL)animated;
-(void)setTransformForCurrentOrientation:(BOOL)currentOrientation;
-(void)deviceOrientationDidChange:(id)deviceOrientation;
-(void)unregisterFromNotifications;
-(void)registerForNotifications;
-(void)updateUIForKeypath:(id)keypath;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(id)observableKeypaths;
-(void)unregisterFromKVO;
-(void)registerForKVO;
-(void)drawRect:(CGRect)rect;
-(void)layoutSubviews;
-(void)updateIndicators;
-(void)setupLabels;
-(void)cleanUp;
-(void)launchExecution;
-(void)showWhileExecuting:(SEL)executing onTarget:(id)target withObject:(id)object animated:(BOOL)animated;
-(void)done;
-(void)animationFinished:(id)finished finished:(BOOL)finished2 context:(void*)context;
-(void)hideUsingAnimation:(BOOL)animation;
-(void)showUsingAnimation:(BOOL)animation;
-(void)handleMinShowTimer:(id)timer;
-(void)handleGraceTimer:(id)timer;
-(void)hideDelayed:(id)delayed;
-(void)hide:(BOOL)hide afterDelay:(double)delay;
-(void)hide:(BOOL)hide;
-(void)show:(BOOL)show;
-(void)dealloc;
-(id)initWithWindow:(id)window;
-(id)initWithView:(id)view;
-(id)initWithFrame:(CGRect)frame;
@end

