/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSURL, NSString, NSMutableArray, NSURLRequest;

__attribute__((visibility("hidden")))
@interface MPOAuthURLRequest : NSObject {
	NSURL* _url;
	NSString* _httpMethod;
	NSURLRequest* _urlRequest;
	NSMutableArray* _parameters;
}
@property(retain, nonatomic) NSMutableArray* parameters;
@property(retain, nonatomic) NSURLRequest* urlRequest;
@property(retain, nonatomic) NSString* HTTPMethod;
@property(retain, nonatomic) NSURL* url;
-(void)addParameters:(id)parameters;
-(id)urlRequestSignedWithSecret:(id)secret usingMethod:(id)method;
-(oneway void)dealloc;
-(id)initWithURLRequest:(id)urlrequest;
-(id)initWithURL:(id)url andParameters:(id)parameters;
@end

