/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;

@protocol MPOAuthCredentialStore <NSObject>
@property(readonly, assign, nonatomic) NSString* accessTokenSecret;
@property(readonly, assign, nonatomic) NSString* accessToken;
@property(readonly, assign, nonatomic) NSString* requestTokenSecret;
@property(readonly, assign, nonatomic) NSString* requestToken;
@property(readonly, assign, nonatomic) NSString* password;
@property(readonly, assign, nonatomic) NSString* username;
@property(readonly, assign, nonatomic) NSString* consumerSecret;
@property(readonly, assign, nonatomic) NSString* consumerKey;
-(void)discardOAuthCredentials;
-(id)credentialNamed:(id)named;
@end

