/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSError, NSString, MPOAuthCredentialConcreteStore, MPOAuthURLRequest, MPOAuthURLResponse, NSData, NSMutableData;
@protocol MPOAuthCredentialStore, MPOAuthParameterFactory;

__attribute__((visibility("hidden")))
@interface MPOAuthAPIRequestLoader : NSObject {
	MPOAuthCredentialConcreteStore* _credentials;
	MPOAuthURLRequest* _oauthRequest;
	MPOAuthURLResponse* _oauthResponse;
	NSMutableData* _dataBuffer;
	NSString* _dataAsString;
	NSError* _error;
	id _target;
	SEL _action;
}
@property(assign, nonatomic) SEL action;
@property(assign, nonatomic) id target;
@property(retain, nonatomic) NSString* responseString;
@property(retain, nonatomic) NSData* data;
@property(retain, nonatomic) MPOAuthURLResponse* oauthResponse;
@property(retain, nonatomic) MPOAuthURLRequest* oauthRequest;
@property(retain, nonatomic) id<MPOAuthCredentialStore, MPOAuthParameterFactory> credentials;
-(void)_interrogateResponseForOAuthData;
-(void)connectionDidFinishLoading:(id)connection;
-(id)connection:(id)connection willSendRequest:(id)request redirectResponse:(id)response;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)loadSynchronously:(BOOL)synchronously;
-(oneway void)dealloc;
-(id)initWithRequest:(id)request;
-(id)initWithURL:(id)url;
@end

