/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MPOAuthAPIInternalClient.h"
#import "MPOAuthAuthenticationMethod.h"

@class NSURL;
@protocol MPOAuthAuthenticationMethodOAuthDelegate;

__attribute__((visibility("hidden")))
@interface MPOAuthAuthenticationMethodOAuth : MPOAuthAuthenticationMethod <MPOAuthAPIInternalClient> {
	NSURL* oauthRequestTokenURL_;
	NSURL* oauthAuthorizeTokenURL_;
	BOOL oauth10aModeActive_;
	id<MPOAuthAuthenticationMethodOAuthDelegate> delegate_;
}
@property(assign, nonatomic) BOOL oauth10aModeActive;
@property(retain, nonatomic) NSURL* oauthAuthorizeTokenURL;
@property(retain, nonatomic) NSURL* oauthRequestTokenURL;
@property(assign, nonatomic) id<MPOAuthAuthenticationMethodOAuthDelegate> delegate;
-(void)_performedLoad:(id)load receivingData:(id)data;
-(void)_accessTokenReceived:(id)received;
-(void)_requestTokenRejected:(id)rejected;
-(void)_requestTokenReceived:(id)received;
-(void)_authenticationRequestForAccessToken;
-(void)_authenticationRequestForUserPermissionsConfirmationAtURL:(id)url;
-(void)loader:(id)loader didFailWithError:(id)error;
-(void)_authenticationRequestForRequestTokenSuccessfulLoad:(id)requestTokenSuccessfulLoad withData:(id)data;
-(void)_authenticationRequestForRequestToken;
-(void)authenticate;
-(oneway void)dealloc;
-(id)initWithAPI:(id)api forURL:(id)url withConfiguration:(id)configuration;
@end

