/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDictionary, NSURLResponse;

__attribute__((visibility("hidden")))
@interface MPOAuthURLResponse : NSObject {
	NSURLResponse* _urlResponse;
	NSDictionary* _oauthParameters;
}
@property(retain, nonatomic) NSDictionary* oauthParameters;
@property(retain, nonatomic) NSURLResponse* urlResponse;
-(oneway void)dealloc;
-(id)init;
@end

