/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURLConnection.h>

@class MPOAuthCredentialConcreteStore;
@protocol MPOAuthCredentialStore, MPOAuthParameterFactory;

__attribute__((visibility("hidden")))
@interface MPOAuthConnection : NSURLConnection {
	MPOAuthCredentialConcreteStore* _credentials;
}
@property(readonly, assign, nonatomic) id<MPOAuthCredentialStore, MPOAuthParameterFactory> credentials;
+(id)sendSynchronousRequest:(id)request usingCredentials:(id)credentials returningResponse:(id*)response error:(id*)error;
+(id)connectionWithRequest:(id)request delegate:(id)delegate credentials:(id)credentials;
-(oneway void)dealloc;
-(id)initWithRequest:(id)request delegate:(id)delegate credentials:(id)credentials;
@end

