/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface MPURLRequestParameter : NSObject {
	NSString* _name;
	NSString* _value;
}
@property(copy, nonatomic) NSString* value;
@property(copy, nonatomic) NSString* name;
+(id)parameterStringForDictionary:(id)dictionary;
+(id)parameterStringForParameters:(id)parameters;
+(id)parameterDictionaryFromString:(id)string;
+(id)parametersFromDictionary:(id)dictionary;
+(id)parametersFromString:(id)string;
-(id)description;
-(int)compare:(id)compare;
-(id)URLEncodedParameterString;
-(oneway void)dealloc;
-(id)initWithName:(id)name andValue:(id)value;
-(id)init;
@end

