/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, ABCodeEditorTemplate, UIImage, NSNumber;

__attribute__((visibility("hidden")))
@interface NewFileInformation : NSObject {
	NSString* _fileName;
	NSNumber* _encodingIndex;
	NSNumber* _typeIndex;
	NSNumber* _lineEndingType;
	NSString* _templateName;
	ABCodeEditorTemplate* _template;
	UIImage* _image;
}
@property(retain, nonatomic) UIImage* image;
@property(retain, nonatomic) ABCodeEditorTemplate* template;
@property(copy, nonatomic) NSString* templateName;
@property(copy, nonatomic) NSNumber* lineEndingType;
@property(copy, nonatomic) NSNumber* encodingIndex;
@property(copy, nonatomic) NSString* fileName;
@property(copy, nonatomic) NSNumber* typeIndex;
-(void)dealloc;
-(id)init;
@end

