/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSDictionary.h>


@interface NSDictionary (JSONKitSerializing)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONStringWithOptions:(unsigned)options error:(id*)error;
-(id)JSONString;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingDelegate:(id)delegate selector:(SEL)selector error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options error:(id*)error;
-(id)JSONData;
@end

@interface NSDictionary (JSONKitSerializingBlockAdditions)
-(id)JSONStringWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
-(id)JSONDataWithOptions:(unsigned)options serializeUnsupportedClassesUsingBlock:(id)block error:(id*)error;
@end

@interface NSDictionary (QueryComponents)
-(id)stringFromQueryComponents;
@end

@interface NSDictionary (SMTENSDictionaryExtensions)
-(id)deeplyMutableCopy;
-(BOOL)boolForKey:(id)key;
-(int)integerForKey:(id)key;
-(unsigned short)unsignedShortForKey:(id)key;
@end

@interface NSDictionary (ABCodeEditorUserDefaultsExtensions)
-(BOOL)boolForKey:(id)key;
-(float)floatForKey:(id)key;
-(int)integerForKey:(id)key;
-(id)dataForKey:(id)key;
-(id)dictionaryForKey:(id)key;
-(id)arrayForKey:(id)key;
-(id)stringForKey:(id)key;
@end

