/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableArray.h>


@interface NSMutableArray (QueueAdditions)
-(void)enqueue:(id)enqueue;
-(id)dequeue;
@end

@interface NSMutableArray (ABCodeEditorStack)
-(id)pop;
-(void)push:(id)push;
@end

