/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableString.h>


@interface NSMutableString (ABCodeEditorAppendCharacter)
-(void)appendCharacter:(unsigned short)character;
@end

@interface NSMutableString (OnigRegexpNSMutableStringUtility)
-(id)replaceAllByRegexp:(id)regexp withBlock:(id)block;
-(id)replaceByRegexp:(id)regexp withBlock:(id)block;
-(id)replaceAllByRegexp:(id)regexp withCallback:(id)callback selector:(SEL)selector;
-(id)replaceByRegexp:(id)regexp withCallback:(id)callback selector:(SEL)selector;
-(id)replaceAllByRegexp:(id)regexp with:(id)with;
-(id)replaceByRegexp:(id)regexp with:(id)with;
@end

