/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableDictionary.h>


@interface NSMutableDictionary (SMTENSMutableDictionaryExtensions)
+(id)deeplyMutableDictionaryWithData:(id)data;
+(id)deeplyMutableDictionaryWithContentsOfFile:(id)file;
-(void)setBool:(BOOL)aBool forKey:(id)key;
-(void)setInteger:(int)integer forKey:(id)key;
-(void)tryToRemoveObjectForKey:(id)key;
@end

@interface NSMutableDictionary (ABCodeEditorUserDefaultsExtensions)
-(void)setString:(id)string forKey:(id)key;
-(void)setBool:(BOOL)aBool forKey:(id)key;
-(void)setFloat:(float)aFloat forKey:(id)key;
-(void)setInteger:(int)integer forKey:(id)key;
@end

