/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSString.h>


@interface NSString (JSONKitDeserializing)
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)mutableObjectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)mutableObjectFromJSONString;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions error:(id*)error;
-(id)objectFromJSONStringWithParseOptions:(unsigned)parseOptions;
-(id)objectFromJSONString;
@end

@interface NSString (JSONKitSerializing)
-(id)JSONStringWithOptions:(unsigned)options includeQuotes:(BOOL)quotes error:(id*)error;
-(id)JSONString;
-(id)JSONDataWithOptions:(unsigned)options includeQuotes:(BOOL)quotes error:(id*)error;
-(id)JSONData;
@end

@interface NSString (RelativePath)
-(id)relativePathFromBaseDirPath:(id)baseDirPath caseSensitive:(BOOL)sensitive;
-(id)relativePathFromBaseDirPath:(id)baseDirPath;
-(id)absolutePathFromBaseDirPath:(id)baseDirPath;
@end

@interface NSString (StringEncoding)
+(int)fillEncodingDescriptionArray:(id)array andValueArray:(id)array2 returningIndexForStringEncoding:(unsigned)stringEncoding;
+(id)advancedLocalizedNameOfStringEncoding:(unsigned)stringEncoding;
@end

@interface NSString (QueryComponents)
-(id)dictionaryFromQueryComponents;
-(id)stringByEncodingURLFormat;
-(id)stringByDecodingURLFormat;
@end

@interface NSString (GTMNSStringHTMLAdditions)
-(id)gtm_stringByUnescapingFromHTML;
-(id)gtm_stringByEscapingForAsciiHTML;
-(id)gtm_stringByEscapingForHTML;
-(id)gtm_stringByEscapingHTMLUsingTable:(XXStruct_c19r_A*)table ofSize:(unsigned)size escapingUnicode:(BOOL)unicode;
@end

@interface NSString (NSString_SBJSON)
-(id)JSONValue;
-(id)JSONFragmentValue;
@end

@interface NSString (MPURLEscapingAdditions)
-(id)stringByAddingURIPercentEscapesUsingEncoding:(unsigned)encoding;
-(BOOL)isIPAddress;
@end

@interface NSString (Dropbox)
-(BOOL)isEqualToDropboxPath:(id)dropboxPath;
-(id)normalizedDropboxPath;
@end

@interface NSString (OnigRegexpNSStringUtility)
-(id)stringByEscapingForRegexp;
-(id)replaceAllByRegexp:(id)regexp withBlock:(id)block;
-(id)replaceAllByRegexp:(id)regexp withCallback:(id)callback selector:(SEL)selector;
-(id)replaceAllByRegexp:(id)regexp with:(id)with;
-(id)__replaceAllByRegexp:(id)regexp withCallback:(/*function-pointer*/ void*)callback data:(void*)data selector:(SEL)selector;
-(id)replaceByRegexp:(id)regexp withBlock:(id)block;
-(id)replaceByRegexp:(id)regexp withCallback:(id)callback selector:(SEL)selector;
-(id)replaceByRegexp:(id)regexp with:(id)with;
-(id)__replaceByRegexp:(id)regexp withCallback:(/*function-pointer*/ void*)callback data:(void*)data selector:(SEL)selector;
-(id)__split:(id)split limit:(id)limit;
-(id)splitByRegexp:(id)regexp limit:(int)limit;
-(id)splitByRegexp:(id)regexp;
-(id)split;
-(NSRange)rangeOfRegexp:(id)regexp;
@end

