/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIControl.h>

@class UIActivityIndicatorView, UIColor, UIScrollView, CAShapeLayer;

__attribute__((visibility("hidden")))
@interface ODRefreshControl : UIControl {
	CAShapeLayer* _shapeLayer;
	CAShapeLayer* _arrowLayer;
	CAShapeLayer* _highlightLayer;
	UIActivityIndicatorView* _activity;
	BOOL _refreshing;
	BOOL _canRefresh;
	UIColor* _tintColor;
	UIScrollView* _scrollView;
}
@property(assign, nonatomic) UIScrollView* scrollView;
@property(retain, nonatomic) UIColor* tintColor;
@property(readonly, assign, nonatomic) BOOL refreshing;
-(void).cxx_destruct;
-(void)endRefreshing;
-(void)beginRefreshing;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)dealloc;
-(void)willMoveToSuperview:(id)superview;
-(id)initInScrollView:(id)scrollView;
@end

