/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface OMUUID : NSObject {
	NSString* uuidString;
}
+(id)createUUIDString;
+(id)uuid;
+(id)uuidWithString:(id)string;
-(id)initNew;
-(id)initWithString:(id)string;
-(id)init;
-(void)dealloc;
-(id)copyWithZone:(NSZone*)zone;
-(BOOL)isEqual:(id)equal;
-(id)uuidString;
-(id)description;
-(unsigned)hash;
@end

