/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableArray, OnigRegexp;

@interface OnigResult : NSObject {
	OnigRegexp* _expression;
	re_registers* _region;
	const char* _target;
	const char* _savedTarget;
	BOOL _targetSaved;
	NSMutableArray* _captureNames;
}
-(id)stringsOfCaptureWithName:(id)name;
-(id)stringOfCaptureWithName:(id)name;
-(id)indexesOfCaptureWithName:(id)name;
-(int)indexOfCaptureWithName:(id)name;
-(id)captureNames;
-(id)captureNameArray;
-(id)stringAfterMatch;
-(id)stringBeforeMatch;
-(unsigned)locationOfMatch;
-(NSRange)rangeOfMatch;
-(id)stringOfMatch;
-(const char*)cStringEndOfMatchAtIndex:(unsigned)index;
-(const char*)cStringBeginOfMatchAtIndex:(unsigned)index;
-(unsigned)lengthOfMatchAtIndex:(unsigned)index;
-(unsigned)locationOfMatchAtIndex:(unsigned)index;
-(NSRange)rangeOfMatchAtIndex:(unsigned)index;
-(id)strings;
-(id)stringOfMatchAtIndex:(unsigned)index;
-(unsigned)count;
-(unsigned)size;
-(id)target;
-(void)saveTarget;
-(BOOL)isEqualToOnigResult:(id)onigResult;
-(void)dealloc;
-(id)initWithRegexp:(id)regexp region:(re_registers*)region target:(const char*)target;
@end

