/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

@interface OnigRegexp : NSObject {
	NSString* _expression;
	re_pattern_buffer* _entity;
	re_registers* _region;
}
+(void)cStringWithString:(id)string andPosition:(unsigned)position start:(const char**)start end:(const char**)end position:(const char**)position5;
+(void)cStringWithString:(id)string start:(const char**)start end:(const char**)end;
+(id)compile:(id)compile options:(int)options;
+(id)compile:(id)compile ignorecase:(BOOL)ignorecase multiline:(BOOL)multiline extended:(BOOL)extended;
+(id)compile:(id)compile ignorecase:(BOOL)ignorecase multiline:(BOOL)multiline;
+(id)compileIgnorecase:(id)ignorecase;
+(id)compile:(id)compile;
-(re_pattern_buffer*)entity;
-(id)expression;
-(id)matchBackwardsCString:(const char*)string stringEnd:(const char*)end matchEnd:(const char*)end3;
-(id)matchCString:(const char*)string stringEnd:(const char*)end start:(const char*)start;
-(id)match:(id)match start:(int)start;
-(id)match:(id)match;
-(id)searchCString:(const char*)string stringEnd:(const char*)end start:(const char*)start end:(const char*)end4;
-(id)search:(id)search range:(NSRange)range;
-(id)search:(id)search start:(int)start end:(int)end;
-(id)search:(id)search start:(int)start;
-(id)search:(id)search;
-(BOOL)reuseRegion:(re_registers*)region;
-(void)dealloc;
-(id)initWithEntity:(re_pattern_buffer*)entity expression:(id)expression;
@end

