/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface PreviewUtility : NSObject {
}
+(id)generateHTMLFromMarkdownFile:(id)markdownFile;
+(BOOL)generateMarkdownPreviewWithInputFile:(id)inputFile outputFile:(id)file bodyOnly:(BOOL)only;
+(id)appVersion;
@end

