/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURLProtocol.h>


__attribute__((visibility("hidden")))
@interface PreviewURLProtocol : NSURLProtocol {
}
+(id)mimeTypeForPathExtension:(id)pathExtension;
+(id)canonicalRequestForRequest:(id)request;
+(BOOL)canInitWithRequest:(id)request;
-(void)stopLoading;
-(void)startLoading;
-(id)initWithRequest:(id)request cachedResponse:(id)response client:(id)client;
@end

