/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface PublicKeyAuthUtils : NSObject {
}
+(BOOL)generatePublicKeyFile:(id)file fromPrivateKeyFile:(id)privateKeyFile passphrase:(id)passphrase error:(id*)error;
@end

