/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface RemoteConnection : NSObject {
	NSString* title;
	NSString* uniqueID;
}
@property(copy, nonatomic) NSString* uniqueID;
@property(copy, nonatomic) NSString* title;
+(id)connectionFromConfigDictionary:(id)configDictionary;
+(id)uuidString;
-(id)imageForConnectionList;
-(void)loadConfigFromDictionary:(id)dictionary;
-(id)configDictionary;
-(int)remoteConnectionType;
-(void)renameFile:(id)file newFileName:(id)name withDelegate:(id)delegate;
-(void)deleteFile:(id)file withDelegate:(id)delegate;
-(void)createDirectory:(id)directory withDelegate:(id)delegate userData:(id)data;
-(void)checkIfFileExistsAt:(id)at withDelegate:(id)delegate userData:(id)data;
-(void)uploadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)downloadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)requestRemoteFileInformationArrayForSubdirectory:(id)subdirectory withDelegate:(id)delegate;
-(id)configurationViewControllerWithMode:(int)mode andDelegate:(id)delegate;
-(id)titleForConnectionList;
-(void)cancelAllRequests;
-(id)navigationItemTitleForPath:(id)path;
-(void)dealloc;
-(id)init;
@end

