/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol RemoteConnectionConfigurationDelegate <NSObject>
-(void)remoteConnection:(id)connection cancelledWithMode:(int)mode;
-(void)remoteConnection:(id)connection savedWithMode:(int)mode;
@end

