/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol RemoteConnectionDelegate <NSObject>
@optional
-(void)remoteConnection:(id)connection renameFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didRenameFile:(id)file;
-(void)remoteConnection:(id)connection deleteFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didDeleteFile:(id)file;
-(void)remoteConnection:(id)connection createDirectory:(id)directory failedWithError:(id)error userData:(id)data;
-(void)remoteConnection:(id)connection didCreateDirectory:(id)directory userData:(id)data;
-(void)remoteConnection:(id)connection checkIfFileExistsAt:(id)at failedWithError:(id)error userData:(id)data;
-(void)remoteConnection:(id)connection fileAt:(id)at exists:(BOOL)exists userData:(id)data;
-(void)remoteConnection:(id)connection uploadFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didUploadFile:(id)file;
-(void)remoteConnection:(id)connection uploadFile:(id)file progressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)remoteConnection:(id)connection downloadFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didDownloadFile:(id)file;
-(void)remoteConnection:(id)connection downloadFile:(id)file progressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)remoteConnection:(id)connection requestRemoteFileInformationArrayFailedWithError:(id)error;
-(void)remoteConnection:(id)connection didReceiveRemoteFileInformationArray:(id)array;
@end

