/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface RemoteFileInformation : NSObject {
	unsigned long long fileSize;
	NSDate* fileModificationDate;
	BOOL marked;
	NSString* fileType;
	NSString* symbolicLinkTarget;
	NSString* basePath;
	NSString* fileName;
	NSString* fileOwnerAccountName;
	NSString* groupOwnerAccountName;
	unsigned long posixPermissions;
	unsigned long referenceCount;
	BOOL directory;
	NSString* completeFilePath;
}
@property(assign, nonatomic) BOOL marked;
@property(copy, nonatomic) NSString* groupOwnerAccountName;
@property(copy, nonatomic) NSString* fileOwnerAccountName;
@property(assign, nonatomic) unsigned long referenceCount;
@property(assign, nonatomic) unsigned long posixPermissions;
@property(copy, nonatomic) NSString* fileType;
@property(copy, nonatomic) NSDate* fileModificationDate;
@property(assign, nonatomic) unsigned long long fileSize;
@property(copy, nonatomic) NSString* symbolicLinkTarget;
@property(readonly, assign, nonatomic) NSString* completeFilePath;
@property(copy, nonatomic) NSString* basePath;
@property(copy, nonatomic) NSString* fileName;
@property(assign, nonatomic, getter=isDirectory) BOOL directory;
+(id)stringForFileSize:(unsigned long long)fileSize;
+(id)remoteFileInformationArrayFromFileListing:(id)fileListing withBasePath:(id)basePath;
+(BOOL)wordIsInteger:(id)integer;
+(int)_filenameColumnIndexFromLine:(id)line dateString:(id)string wordArray:(id)array;
+(id)getDateFromMonth:(id)month day:(id)day yearOrTime:(id)time;
+(void)parsePermissions:(id)permissions withRemoteFileInformation:(id)remoteFileInformation;
+(void)parseFilenameAndSymbolicLinksFromIndex:(int)index ofWords:(id)words withRemoteFileInformation:(id)remoteFileInformation;
+(id)fixFilename:(id)filename withRemoteFileInformation:(id)remoteFileInformation;
+(id)_wordsFromLine:(id)line dateString:(id)string;
+(id)_dateStringFromListing:(id)listing;
+(id)remoteFileInformation;
-(void)dealloc;
-(id)fileIcon;
-(BOOL)isImageExtension:(id)extension;
-(id)fileModificationDateString;
-(id)fileSizeString;
-(int)compare:(id)compare;
@end

