/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "RemoteConnectionDelegate.h"
#import <UIKit/UITableViewController.h>
#import "AddFileViewControllerDelegate.h"
#import "RenameFileViewControllerDelegate.h"

@class NSMutableArray, NSString, UIActionSheet, RemoteConnection, UIBarButtonItem, ODRefreshControl;

__attribute__((visibility("hidden")))
@interface RemoteDirectoryViewController : UITableViewController <RemoteConnectionDelegate, AddFileViewControllerDelegate, UIActionSheetDelegate, RenameFileViewControllerDelegate> {
	NSMutableArray* remoteFileInformationArray;
	RemoteConnection* connection;
	NSString* path;
	UIBarButtonItem* downloadButton;
	UIActionSheet* fileActionSheet;
	ODRefreshControl* refreshControl;
}
@property(readonly, assign, nonatomic) NSString* path;
@property(retain, nonatomic) NSMutableArray* remoteFileInformationArray;
@property(retain, nonatomic) RemoteConnection* connection;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(BOOL)renameRemoteFile:(id)file newFileName:(id)name;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)contentViewLongPress:(id)press;
-(void)contentViewTap:(id)tap;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)makeRenameButton:(BOOL)button;
-(void)renameButtonTapped:(id)tapped withEvent:(id)event;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)remoteConnection:(id)connection deleteFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection renameFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didRenameFile:(id)file;
-(void)remoteConnection:(id)connection createDirectory:(id)directory failedWithError:(id)error userData:(id)data;
-(void)remoteConnection:(id)connection didCreateDirectory:(id)directory userData:(id)data;
-(void)remoteConnection:(id)connection requestRemoteFileInformationArrayFailedWithError:(id)error;
-(void)remoteConnection:(id)connection didReceiveRemoteFileInformationArray:(id)array;
-(void)viewWillAppear:(BOOL)view;
-(void)refreshAction:(id)action;
-(void)downloadAction:(id)action;
-(void)downloadSelectedFilesToDirectory:(id)directory;
-(void)fileActionAction:(id)action;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)addMarkedFilesToTransferProgressViewControllerAndShow:(id)transferProgressViewControllerAndShow;
-(int)numberOfMarkedFiles;
-(BOOL)addFileViewController:(id)controller insertNewFileInformation:(id)information;
-(void)addAction:(id)action;
-(BOOL)dismissFileActionSheet;
-(void)updateButtons;
-(void)viewDidLoad;
-(void)selectAll:(BOOL)all;
-(void)refreshFileList;
-(void)refreshToolbarItems;
-(id)flexibleSpace;
-(id)initWithPathOrNil:(id)pathOrNil;
@end

