/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"
#import "SCTableViewModelDelegate.h"

@class RemoteFileInformation, FileInformation;
@protocol RenameFileViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface RenameFileViewController : SCTableViewController <SCTableViewModelDelegate> {
	FileInformation* file;
	RemoteFileInformation* remoteFile;
	id<RenameFileViewControllerDelegate> renameFileViewControllerDelegate;
	BOOL copy;
}
@property(assign, nonatomic) id<RenameFileViewControllerDelegate> renameFileViewControllerDelegate;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)doneButtonAction;
-(BOOL)tableViewModel:(id)model valueIsValidForRowAtIndexPath:(id)indexPath;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType withRemoteFile:(id)remoteFile copy:(BOOL)copy;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType withFile:(id)file copy:(BOOL)copy;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType withFile:(id)file withRemoteFile:(id)remoteFile copy:(BOOL)copy;
@end

