/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJsonBase.h"
#import "SBJsonWriter.h"


@protocol SBJsonWriter
@property(assign) BOOL sortKeys;
@property(assign) BOOL humanReadable;
-(id)stringWithObject:(id)object;
@end

__attribute__((visibility("hidden")))
@interface SBJsonWriter : SBJsonBase <SBJsonWriter> {
	BOOL sortKeys;
	BOOL humanReadable;
}
@property(assign) BOOL sortKeys;
@property(assign) BOOL humanReadable;
+(void)initialize;
-(BOOL)appendString:(id)string into:(id)into;
-(BOOL)appendDictionary:(id)dictionary into:(id)into;
-(BOOL)appendArray:(id)array into:(id)into;
-(BOOL)appendValue:(id)value into:(id)into;
-(id)indent;
-(id)stringWithObject:(id)object;
-(id)stringWithFragment:(id)fragment;
@end

