/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SBJsonParser.h"
#import "SBJsonBase.h"


@protocol SBJsonParser
-(id)objectWithString:(id)string;
@end

__attribute__((visibility("hidden")))
@interface SBJsonParser : SBJsonBase <SBJsonParser> {
	const char* c;
}
+(void)initialize;
-(BOOL)scanIsAtEnd;
-(BOOL)scanNumber:(id*)number;
-(BOOL)scanHexQuad:(unsigned short*)quad;
-(BOOL)scanUnicodeChar:(unsigned short*)aChar;
-(BOOL)scanRestOfString:(id*)string;
-(BOOL)scanRestOfDictionary:(id*)dictionary;
-(BOOL)scanRestOfArray:(id*)array;
-(BOOL)scanRestOfNull:(id*)null;
-(BOOL)scanRestOfFalse:(id*)aFalse;
-(BOOL)scanRestOfTrue:(id*)aTrue;
-(BOOL)scanValue:(id*)value;
-(id)objectWithString:(id)string;
-(id)fragmentWithString:(id)string;
@end

