/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSArray, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SBJsonBase : NSObject {
	NSMutableArray* errorTrace;
	unsigned depth;
	unsigned maxDepth;
}
@property(readonly, assign) NSArray* errorTrace;
@property(assign) unsigned maxDepth;
-(void)clearErrorTrace;
-(void)addErrorWithCode:(unsigned)code description:(id)description;
-(void)dealloc;
-(id)init;
@end

