/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCArrayOfItemsSection.h"


__attribute__((visibility("hidden")))
@interface SCArrayOfStringsSection : SCArrayOfItemsSection {
}
-(void)tableViewControllerDidDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)commitDetailModelChanges:(id)changes;
-(void)addNewItem:(id)item;
-(void)buildDetailTableModel:(id)model forItem:(id)item;
-(id)createNewItem;
-(id)textForCellAtIndex:(unsigned)index;
@end

