/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewControllerDelegate.h"
#import "SCTableViewModel.h"
#import "Textastic-Structs.h"

@class SCArrayOfItemsSection, NSMutableArray, UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface SCArrayOfItemsModel : SCTableViewModel <SCTableViewControllerDelegate> {
	SCArrayOfItemsSection* tempSection;
	NSMutableArray* items;
	int itemsAccessoryType;
	BOOL allowAddingItems;
	BOOL allowDeletingItems;
	BOOL allowMovingItems;
	BOOL allowEditDetailView;
	BOOL allowRowSelection;
	BOOL detailViewModal;
	int detailViewModalPresentationStyle;
	int detailTableViewStyle;
	BOOL detailViewHidesBottomBar;
	UIBarButtonItem* addButtonItem;
}
@property(retain, nonatomic) UIBarButtonItem* addButtonItem;
@property(assign, nonatomic) BOOL detailViewHidesBottomBar;
@property(assign, nonatomic) int detailTableViewStyle;
@property(assign, nonatomic) int detailViewModalPresentationStyle;
@property(assign, nonatomic) BOOL detailViewModal;
@property(assign, nonatomic) BOOL allowRowSelection;
@property(assign, nonatomic) BOOL allowEditDetailView;
@property(assign, nonatomic) BOOL allowMovingItems;
@property(assign, nonatomic) BOOL allowDeletingItems;
@property(assign, nonatomic) BOOL allowAddingItems;
@property(assign, nonatomic) int itemsAccessoryType;
@property(retain, nonatomic) NSMutableArray* items;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)addNewItem:(id)item;
-(void)didTapAddButtonItem;
-(void)setAutoSortSections:(BOOL)sections;
-(void)setPropertiesForSection:(id)section;
-(id)createSectionWithHeaderTitle:(id)headerTitle;
-(id)getHeaderTitleForItemAtIndex:(unsigned)index;
-(void)generateSections;
-(void)dealloc;
-(id)initWithTableView:(id)tableView withViewController:(id)viewController withItems:(id)items;
-(id)init;
@end

