/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCObjectAttributes.h"


__attribute__((visibility("hidden")))
@interface SCArrayOfObjectsAttributes : SCObjectAttributes {
	BOOL allowAddingItems;
	BOOL allowDeletingItems;
	BOOL allowMovingItems;
	BOOL allowEditingItems;
}
@property(assign, nonatomic) BOOL allowEditingItems;
@property(assign, nonatomic) BOOL allowMovingItems;
@property(assign, nonatomic) BOOL allowDeletingItems;
@property(assign, nonatomic) BOOL allowAddingItems;
+(id)attributesWithObjectClassDefinition:(id)objectClassDefinition allowAddingItems:(BOOL)items allowDeletingItems:(BOOL)items3 allowMovingItems:(BOOL)items4;
-(id)initWithObjectClassDefinition:(id)objectClassDefinition allowAddingItems:(BOOL)items allowDeletingItems:(BOOL)items3 allowMovingItems:(BOOL)items4;
-(id)init;
@end

