/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCObjectCell.h"

@class NSMutableSet, NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SCArrayOfObjectsCell : SCObjectCell {
	NSMutableArray* items;
	NSMutableSet* itemsSet;
	BOOL sortItemsSetAscending;
	NSMutableDictionary* itemsClassDefinitions;
	BOOL allowAddingItems;
	BOOL allowDeletingItems;
	BOOL allowMovingItems;
	BOOL allowEditDetailView;
	BOOL allowRowSelection;
	BOOL displayItemsCountInBadgeView;
}
@property(assign, nonatomic) BOOL displayItemsCountInBadgeView;
@property(assign, nonatomic) BOOL allowRowSelection;
@property(assign, nonatomic) BOOL allowEditDetailView;
@property(assign, nonatomic) BOOL allowMovingItems;
@property(assign, nonatomic) BOOL allowDeletingItems;
@property(assign, nonatomic) BOOL allowAddingItems;
@property(readonly, assign, nonatomic) NSMutableDictionary* itemsClassDefinitions;
@property(assign, nonatomic) BOOL sortItemsSetAscending;
@property(retain, nonatomic) NSMutableSet* itemsSet;
@property(retain, nonatomic) NSMutableArray* items;
+(id)cellWithItemsSet:(id)itemsSet withClassDefinition:(id)classDefinition;
+(id)cellWithItems:(id)items withClassDefinition:(id)classDefinition;
-(void)tableViewControllerDidDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillAppear:(id)tableViewController;
-(void)setAttributesTo:(id)to;
-(void)didSelectCell;
-(void)willDisplay;
-(void)commitDetailModelChanges:(id)changes;
-(void)addObjectsSectionToModel:(id)model;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithItemsSet:(id)itemsSet withClassDefinition:(id)classDefinition;
-(id)initWithItems:(id)items withClassDefinition:(id)classDefinition;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

