/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont;

__attribute__((visibility("hidden")))
@interface SCBadgeView : UIView {
	UIColor* color;
	NSString* text;
	UIFont* font;
}
@property(retain, nonatomic) UIFont* font;
@property(copy, nonatomic) NSString* text;
@property(retain, nonatomic) UIColor* color;
-(void)drawRect:(CGRect)rect;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

