/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface SCClassDefinition : NSObject {
	Class cls;
	NSMutableArray* propertyDefinitions;
	NSString* keyPropertyName;
	NSString* titlePropertyName;
	NSString* titlePropertyNameDelimiter;
	NSString* descriptionPropertyName;
	id uiElementDelegate;
}
@property(readonly, assign, nonatomic) unsigned propertyDefinitionCount;
@property(assign, nonatomic) id uiElementDelegate;
@property(copy, nonatomic) NSString* descriptionPropertyName;
@property(copy, nonatomic) NSString* titlePropertyNameDelimiter;
@property(copy, nonatomic) NSString* titlePropertyName;
@property(copy, nonatomic) NSString* keyPropertyName;
@property(readonly, assign, nonatomic) NSString* className;
@property(readonly, assign, nonatomic) Class cls;
+(id)definitionWithClass:(Class)aClass withPropertyNames:(id)propertyNames withPropertyTitles:(id)propertyTitles;
+(id)definitionWithClass:(Class)aClass withPropertyNames:(id)propertyNames;
+(id)definitionWithClass:(Class)aClass autoGeneratePropertyDefinitions:(BOOL)definitions;
-(id)titleValueForObject:(id)object;
-(BOOL)isValidPropertyName:(id)name;
-(unsigned)indexOfPropertyDefinitionWithName:(id)name;
-(id)propertyDefinitionWithName:(id)name;
-(id)propertyDefinitionAtIndex:(unsigned)index;
-(void)removePropertyDefinitionWithName:(id)name;
-(void)removePropertyDefinitionAtIndex:(unsigned)index;
-(BOOL)addPropertyDefinition:(id)definition;
-(BOOL)addPropertyDefinitionWithName:(id)name title:(id)title type:(int)type;
-(id)getUserFriendlyPropertyTitleFromName:(id)name;
-(void)dealloc;
-(id)initWithClass:(Class)aClass withPropertyNames:(id)propertyNames withPropertyTitles:(id)propertyTitles;
-(id)initWithClass:(Class)aClass withPropertyNames:(id)propertyNames;
-(id)initWithClass:(Class)aClass autoGeneratePropertyDefinitions:(BOOL)definitions;
-(id)init;
@end

