/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCViewControllerDelegate.h"
#import "SCLabelCell.h"

@class UIDatePicker, NSDateFormatter;

__attribute__((visibility("hidden")))
@interface SCDateCell : SCLabelCell <SCViewControllerDelegate> {
	UIDatePicker* datePicker;
	NSDateFormatter* dateFormatter;
	BOOL displaySelectedDate;
	BOOL allowDetailView;
	BOOL detailViewModal;
}
@property(assign, nonatomic) BOOL detailViewModal;
@property(assign, nonatomic) BOOL allowDetailView;
@property(assign, nonatomic) BOOL displaySelectedDate;
@property(retain, nonatomic) NSDateFormatter* dateFormatter;
@property(readonly, assign, nonatomic) UIDatePicker* datePicker;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withDateValue:(id)dateValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withDatePropertyName:(id)datePropertyName;
-(void)viewControllerDidDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerWillDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerWillAppear:(id)viewController;
-(void)willDeselectCell;
-(void)didSelectCell;
-(id)getCustomDetailViewForRowAtIndexPath:(id)indexPath;
-(BOOL)getValueIsValid;
-(void)setAttributesTo:(id)to;
-(void)commitChanges;
-(void)commitDetailViewChanges;
-(void)cellValueChanged;
-(void)loadBoundValueIntoControl;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withDateValue:(id)dateValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withDatePropertyName:(id)datePropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

