/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"

@class NSDateFormatter;

__attribute__((visibility("hidden")))
@interface SCDateAttributes : SCPropertyAttributes {
	NSDateFormatter* dateFormatter;
}
@property(retain, nonatomic) NSDateFormatter* dateFormatter;
+(id)attributesWithDateFormatter:(id)dateFormatter;
-(void)dealloc;
-(id)initWithDateFormatter:(id)dateFormatter;
-(id)init;
@end

