/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCViewControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "SCTableViewCell.h"

@class NSString, UIImage, UIImagePickerController;

__attribute__((visibility("hidden")))
@interface SCImagePickerCell : SCTableViewCell <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIActionSheetDelegate, SCViewControllerDelegate> {
	UIImage* cachedImage;
	UIImagePickerController* imagePickerController;
	NSString* placeholderImageName;
	BOOL displayImageNameAsCellText;
	BOOL askForSourceType;
	NSString* selectedImageName;
}
@property(retain, nonatomic) NSString* selectedImageName;
@property(assign, nonatomic) BOOL askForSourceType;
@property(assign, nonatomic) BOOL displayImageNameAsCellText;
@property(retain, nonatomic) NSString* placeholderImageName;
@property(readonly, assign, nonatomic) UIImage* selectedImage;
@property(readonly, assign, nonatomic) UIImagePickerController* imagePickerController;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withImageNameValue:(id)imageNameValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withImageNamePropertyName:(id)imageNamePropertyName;
-(void)viewControllerWillDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerWillAppear:(id)viewController;
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;
-(void)imagePickerControllerDidCancel:(id)imagePickerController;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)displayImagePicker;
-(void)displayImageInDetailView;
-(void)didSelectCell;
-(BOOL)getValueIsValid;
-(void)commitChanges;
-(void)layoutSubviews;
-(id)selectedImagePath;
-(void)setCachedImage;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withImageNameValue:(id)imageNameValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withImageNamePropertyName:(id)imageNamePropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

