/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCControlCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface SCLabelCell : SCControlCell {
}
@property(readonly, assign, nonatomic) UILabel* label;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withLabelTextValue:(id)labelTextValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withLabelTextPropertyName:(id)labelTextPropertyName;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(void)setBackgroundColor:(id)color;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withLabelTextValue:(id)labelTextValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withLabelTextPropertyName:(id)labelTextPropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

