/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTextFieldAttributes.h"

@class NSNumber;

__attribute__((visibility("hidden")))
@interface SCNumericTextFieldAttributes : SCTextFieldAttributes {
	NSNumber* minimumValue;
	NSNumber* maximumValue;
	BOOL allowFloatValue;
}
@property(assign, nonatomic) BOOL allowFloatValue;
@property(copy, nonatomic) NSNumber* maximumValue;
@property(copy, nonatomic) NSNumber* minimumValue;
+(id)attributesWithMinimumValue:(id)minimumValue maximumValue:(id)value allowFloatValue:(BOOL)value3 placeholder:(id)placeholder;
+(id)attributesWithMinimumValue:(id)minimumValue maximumValue:(id)value allowFloatValue:(BOOL)value3;
-(void)dealloc;
-(id)initWithMinimumValue:(id)minimumValue maximumValue:(id)value allowFloatValue:(BOOL)value3 placeholder:(id)placeholder;
-(id)initWithMinimumValue:(id)minimumValue maximumValue:(id)value allowFloatValue:(BOOL)value3;
-(id)init;
@end

