/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface SCObjectAttributes : SCPropertyAttributes {
	NSMutableDictionary* classDefinitions;
}
@property(readonly, assign, nonatomic) NSMutableDictionary* classDefinitions;
+(id)attributesWithObjectClassDefinition:(id)objectClassDefinition;
-(void)dealloc;
-(id)initWithObjectClassDefinition:(id)objectClassDefinition;
-(id)init;
@end

