/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewControllerDelegate.h"
#import "SCTableViewCell.h"

@class NSString, SCClassDefinition;

__attribute__((visibility("hidden")))
@interface SCObjectCell : SCTableViewCell <SCTableViewControllerDelegate> {
	SCClassDefinition* objectClassDefinition;
	NSString* boundObjectTitleText;
	BOOL allowDetailView;
	BOOL detailViewModal;
}
@property(assign, nonatomic) BOOL detailViewModal;
@property(assign, nonatomic) BOOL allowDetailView;
@property(copy, nonatomic) NSString* boundObjectTitleText;
@property(retain, nonatomic) SCClassDefinition* objectClassDefinition;
+(id)cellWithBoundObject:(id)boundObject withClassDefinition:(id)classDefinition;
+(id)cellWithBoundObject:(id)boundObject;
-(void)tableViewControllerDidDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillAppear:(id)tableViewController;
-(void)setCellTextAndDetailText;
-(void)setBoundPropertyName:(id)name;
-(void)setAttributesTo:(id)to;
-(void)didSelectCell;
-(void)commitDetailModelChanges:(id)changes;
-(void)addObjectSectionToModel:(id)model;
-(void)cellValueChanged;
-(void)willDisplay;
-(void)dealloc;
-(id)initWithBoundObject:(id)boundObject withClassDefinition:(id)classDefinition;
-(id)initWithBoundObject:(id)boundObject;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

