/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCSelectionAttributes.h"

@class NSString, SCClassDefinition;

__attribute__((visibility("hidden")))
@interface SCObjectSelectionAttributes : SCSelectionAttributes {
	SCClassDefinition* itemsEntityClassDefinition;
	NSString* itemsTitlePropertyName;
}
@property(retain, nonatomic) NSString* itemsTitlePropertyName;
@property(retain, nonatomic) SCClassDefinition* itemsEntityClassDefinition;
+(id)attributesWithItemsEntityClassDefinition:(id)itemsEntityClassDefinition withItemsTitlePropertyName:(id)itemsTitlePropertyName allowMultipleSelection:(BOOL)selection allowNoSelection:(BOOL)selection4;
-(void)dealloc;
-(id)initWithItemsEntityClassDefinition:(id)itemsEntityClassDefinition withItemsTitlePropertyName:(id)itemsTitlePropertyName allowMultipleSelection:(BOOL)selection allowNoSelection:(BOOL)selection4;
-(id)init;
@end

