/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewSection.h"

@class SCClassDefinition;

__attribute__((visibility("hidden")))
@interface SCObjectSection : SCTableViewSection {
	SCClassDefinition* boundObjectClassDefinition;
}
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withClassDefinition:(id)classDefinition;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject;
-(id)cellForPropertyName:(id)propertyName;
-(id)getCellForPropertyWithDefinition:(id)definition withUIElementDelegate:(id)uielementDelegate;
-(void)dealloc;
-(id)initWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withClassDefinition:(id)classDefinition;
-(id)initWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject;
@end

