/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCSelectionCell.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SCObjectSelectionCell : SCSelectionCell {
	NSString* titlePropertyName;
}
@property(retain, nonatomic) NSString* titlePropertyName;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withSelectedObjectPropertyName:(id)selectedObjectPropertyName withItems:(id)items withItemTitlePropertyName:(id)itemTitlePropertyName;
-(void)commitChanges;
-(id)createSelectionSection;
-(id)getTitleForItemAtIndex:(unsigned)index;
-(void)setAttributesTo:(id)to;
-(void)dealloc;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withSelectedObjectPropertyName:(id)selectedObjectPropertyName withItems:(id)items withItemTitlePropertyName:(id)itemTitlePropertyName;
@end

