/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIImageView, NSArray;

__attribute__((visibility("hidden")))
@interface SCPropertyAttributes : NSObject {
	UIImageView* imageView;
	NSArray* imageViewArray;
}
@property(retain, nonatomic) NSArray* imageViewArray;
@property(retain, nonatomic) UIImageView* imageView;
-(void)dealloc;
-(id)init;
@end

