/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"

@class NSArray;

__attribute__((visibility("hidden")))
@interface SCSegmentedAttributes : SCPropertyAttributes {
	NSArray* segmentTitlesArray;
}
@property(retain, nonatomic) NSArray* segmentTitlesArray;
+(id)attributesWithSegmentTitlesArray:(id)segmentTitlesArray;
-(void)dealloc;
-(id)initWithSegmentTitlesArray:(id)segmentTitlesArray;
-(id)init;
@end

