/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCControlCell.h"

@class UISegmentedControl;

__attribute__((visibility("hidden")))
@interface SCSegmentedCell : SCControlCell {
}
@property(readonly, assign, nonatomic) UISegmentedControl* segmentedControl;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withSelectedSegmentIndexValue:(id)selectedSegmentIndexValue withSegmentTitlesArray:(id)segmentTitlesArray;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withSelectedSegmentIndexPropertyName:(id)selectedSegmentIndexPropertyName withSegmentTitlesArray:(id)segmentTitlesArray;
-(void)segmentedControlValueChanged;
-(void)createSegmentsUsingArray:(id)array;
-(BOOL)getValueIsValid;
-(void)setAttributesTo:(id)to;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withSelectedSegmentIndexValue:(id)selectedSegmentIndexValue withSegmentTitlesArray:(id)segmentTitlesArray;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withSelectedSegmentIndexPropertyName:(id)selectedSegmentIndexPropertyName withSegmentTitlesArray:(id)segmentTitlesArray;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

