/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCArrayOfItemsSection.h"

@class NSMutableSet, NSIndexPath, NSNumber;

__attribute__((visibility("hidden")))
@interface SCSelectionSection : SCArrayOfItemsSection {
	BOOL boundToNSNumber;
	BOOL boundToNSString;
	NSIndexPath* lastSelectedRowIndexPath;
	BOOL allowMultipleSelection;
	BOOL allowNoSelection;
	BOOL autoDismissViewController;
	NSMutableSet* _selectedItemsIndexes;
}
@property(assign, nonatomic) BOOL autoDismissViewController;
@property(assign, nonatomic) BOOL allowNoSelection;
@property(assign, nonatomic) BOOL allowMultipleSelection;
@property(readonly, assign, nonatomic) NSMutableSet* selectedItemsIndexes;
@property(copy, nonatomic) NSNumber* selectedItemIndex;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundKey:(id)boundKey withSelectedIndexesValue:(id)selectedIndexesValue withItems:(id)items allowMultipleSelection:(BOOL)selection;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundKey:(id)boundKey withSelectedIndexValue:(id)selectedIndexValue withItems:(id)items;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectionStringPropertyName:(id)selectionStringPropertyName withItems:(id)items;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectedIndexesPropertyName:(id)selectedIndexesPropertyName withItems:(id)items allowMultipleSelection:(BOOL)selection;
+(id)sectionWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectedIndexPropertyName:(id)selectedIndexPropertyName withItems:(id)items;
-(void)dismissViewController;
-(void)didSelectCellAtIndexPath:(id)indexPath;
-(void)deselectLastSelectedRow;
-(id)textForCellAtIndex:(unsigned)index;
-(id)cellAtIndex:(unsigned)index;
-(id)buildStringFromSelectedItemsIndexes;
-(void)buildSelectedItemsIndexesFromString:(id)string;
-(void)dealloc;
-(id)initWithHeaderTitle:(id)headerTitle withBoundKey:(id)boundKey withSelectedIndexesValue:(id)selectedIndexesValue withItems:(id)items allowMultipleSelection:(BOOL)selection;
-(id)initWithHeaderTitle:(id)headerTitle withBoundKey:(id)boundKey withSelectedIndexValue:(id)selectedIndexValue withItems:(id)items;
-(id)initWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectionStringPropertyName:(id)selectionStringPropertyName withItems:(id)items;
-(id)initWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectedIndexesPropertyName:(id)selectedIndexesPropertyName withItems:(id)items allowMultipleSelection:(BOOL)selection;
-(id)initWithHeaderTitle:(id)headerTitle withBoundObject:(id)boundObject withSelectedIndexPropertyName:(id)selectedIndexPropertyName withItems:(id)items;
-(id)init;
@end

