/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCControlCell.h"

@class UISlider;

__attribute__((visibility("hidden")))
@interface SCSliderCell : SCControlCell {
}
@property(readonly, assign, nonatomic) UISlider* slider;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withSliderValue:(id)sliderValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withSliderValuePropertyName:(id)sliderValuePropertyName;
-(void)sliderValueChanged;
-(void)setAttributesTo:(id)to;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withSliderValue:(id)sliderValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withSliderValuePropertyName:(id)sliderValuePropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

