/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"


__attribute__((visibility("hidden")))
@interface SCSliderAttributes : SCPropertyAttributes {
	float minimumValue;
	float maximumValue;
}
@property(assign, nonatomic) float maximumValue;
@property(assign, nonatomic) float minimumValue;
+(id)attributesWithMinimumValue:(float)minimumValue maximumValue:(float)value;
-(void)dealloc;
-(id)initWithMinimumValue:(float)minimumValue maximumValue:(float)value;
-(id)init;
@end

