/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCControlCell.h"

@class UISwitch;

__attribute__((visibility("hidden")))
@interface SCSwitchCell : SCControlCell {
}
@property(readonly, assign, nonatomic) UISwitch* switchControl;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withSwitchOnValue:(id)switchOnValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withSwitchOnPropertyName:(id)switchOnPropertyName;
-(void)switchControlChanged;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withSwitchOnValue:(id)switchOnValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withSwitchOnPropertyName:(id)switchOnPropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

