/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SCTableViewCellDelegate
@optional
-(void)detailViewDidDisappearForCell:(id)detailView;
-(void)detailViewWillAppearForCell:(id)detailView withDetailTableViewModel:(id)detailTableViewModel;
-(id)newImageNameForCell:(id)cell;
-(void)returnButtonTappedForCell:(id)cell;
-(BOOL)valueIsValidForCell:(id)cell;
-(void)accessoryButtonTappedForCell:(id)cell;
-(void)didDeselectCell:(id)cell;
-(void)didSelectCell:(id)cell;
-(void)willSelectCell:(id)cell;
-(void)willDisplayCell:(id)cell;
-(void)willConfigureCell:(id)cell;
@end

