/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import <Foundation/NSObject.h>
#import "UITableViewDelegate.h"
#import "Textastic-Structs.h"

@class NSIndexPath, NSMutableArray, NSMutableDictionary, UIViewController, NSArray, UIBarButtonItem, SCTableViewCell, UITableView;

__attribute__((visibility("hidden")))
@interface SCTableViewModel : NSObject <UITableViewDataSource, UITableViewDelegate> {
	id target;
	SEL action;
	SCTableViewModel* masterModel;
	UITableView* modeledTableView;
	UIViewController* viewController;
	id dataSource;
	id delegate;
	UIBarButtonItem* editButtonItem;
	BOOL autoResizeForKeyboard;
	BOOL autoResizeStatus;
	BOOL keyboardShown;
	float keyboardOverlap;
	NSMutableArray* sections;
	NSArray* sectionIndexTitles;
	BOOL autoGenerateSectionIndexTitles;
	BOOL autoSortSections;
	BOOL lockCellSelection;
	int tag;
	SCTableViewCell* previousActiveCell;
	SCTableViewCell* activeCell;
	NSMutableDictionary* modelKeyValues;
	UIBarButtonItem* commitButton;
}
@property(assign, nonatomic) SCTableViewModel* masterModel;
@property(readonly, assign, nonatomic) UIViewController* viewController;
@property(readonly, assign, nonatomic) UITableView* modeledTableView;
@property(assign, nonatomic) id delegate;
@property(assign, nonatomic) id dataSource;
@property(retain, nonatomic) UIBarButtonItem* commitButton;
@property(readonly, assign, nonatomic) BOOL valuesAreValid;
@property(readonly, assign, nonatomic) NSMutableDictionary* modelKeyValues;
@property(readonly, assign, nonatomic) NSIndexPath* activeCellIndexPath;
@property(assign, nonatomic) SCTableViewCell* activeCell;
@property(readonly, assign, nonatomic) SCTableViewCell* previousActiveCell;
@property(readonly, assign, nonatomic) unsigned sectionCount;
@property(assign, nonatomic) int tag;
@property(assign, nonatomic) BOOL lockCellSelection;
@property(assign, nonatomic) BOOL autoSortSections;
@property(assign, nonatomic) BOOL autoGenerateSectionIndexTitles;
@property(retain, nonatomic) NSArray* sectionIndexTitles;
@property(assign, nonatomic) BOOL autoResizeForKeyboard;
@property(retain, nonatomic) UIBarButtonItem* editButtonItem;
+(id)tableViewModelWithTableView:(id)tableView withViewController:(id)viewController;
-(void)tableAnimationEnded:(id)ended finished:(id)finished contextInfo:(void*)info;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)unregisterKeyboardNotifications;
-(void)registerForKeyboardNotifications;
-(void)tableView:(id)view accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)tableView:(id)view didDeselectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willDeselectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view sectionForSectionIndexTitle:(id)sectionIndexTitle atIndex:(int)index;
-(id)sectionIndexTitlesForTableView:(id)tableView;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)resumeAutoResizeForKeyboard;
-(void)pauseAutoResizeForKeyboard;
-(void)reloadBoundValues;
-(id)cellAfterCell:(id)cell rewindIfLastCell:(BOOL)cell2;
-(id)indexPathForCell:(id)cell;
-(id)cellAtIndexPath:(id)indexPath;
-(void)clear;
-(void)removeAllSections;
-(void)removeSectionAtIndex:(unsigned)index;
-(unsigned)indexForSection:(id)section;
-(id)sectionWithHeaderTitle:(id)headerTitle;
-(id)sectionAtIndex:(unsigned)index;
-(void)insertSection:(id)section atIndex:(unsigned)index;
-(void)addSection:(id)section;
-(void)replaceModeledTableViewWith:(id)with;
-(void)didTapEditButtonItem;
-(void)setTargetForModelModifiedEvent:(id)modelModifiedEvent action:(SEL)action;
-(void)valueChangedForRowAtIndexPath:(id)indexPath;
-(void)valueChangedForSectionAtIndex:(unsigned)index;
-(void)dealloc;
-(id)initWithTableView:(id)tableView withViewController:(id)viewController;
@end

