/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSMutableArray, UIView, SCTableViewModel, NSArray;

__attribute__((visibility("hidden")))
@interface SCTableViewSection : NSObject {
	id ownerViewControllerDelegate;
	SCTableViewModel* ownerTableViewModel;
	NSObject* boundObject;
	NSString* boundPropertyName;
	NSString* boundKey;
	NSObject* initialValue;
	BOOL commitCellChangesLive;
	BOOL coreDataBound;
	NSString* headerTitle;
	float headerHeight;
	UIView* headerView;
	NSString* footerTitle;
	float footerHeight;
	UIView* footerView;
	NSMutableArray* cells;
	NSArray* cellsImageViews;
}
@property(retain, nonatomic) NSObject* boundValue;
@property(readonly, assign, nonatomic) NSString* boundKey;
@property(readonly, assign, nonatomic) NSString* boundPropertyName;
@property(readonly, assign, nonatomic) NSObject* boundObject;
@property(assign, nonatomic) BOOL commitCellChangesLive;
@property(readonly, assign, nonatomic) BOOL valuesAreValid;
@property(readonly, assign, nonatomic) unsigned cellCount;
@property(retain, nonatomic) NSArray* cellsImageViews;
@property(retain, nonatomic) UIView* footerView;
@property(assign, nonatomic) float footerHeight;
@property(copy, nonatomic) NSString* footerTitle;
@property(retain, nonatomic) UIView* headerView;
@property(assign, nonatomic) float headerHeight;
@property(copy, nonatomic) NSString* headerTitle;
@property(assign, nonatomic) SCTableViewModel* ownerTableViewModel;
+(id)sectionWithHeaderTitle:(id)headerTitle withFooterTitle:(id)footerTitle;
+(id)sectionWithHeaderTitle:(id)headerTitle;
+(id)section;
-(void)enableOwnerViewControllerDelegate;
-(void)disableOwnerViewControllerDelegate;
-(void)reloadBoundValues;
-(void)commitCellChanges;
-(unsigned)indexForCell:(id)cell;
-(void)removeCellAtIndex:(unsigned)index;
-(id)cellAtIndex:(unsigned)index;
-(void)insertCell:(id)cell atIndex:(unsigned)index;
-(void)addCell:(id)cell;
-(int)compare:(id)compare;
-(void)dealloc;
-(id)initWithHeaderTitle:(id)headerTitle withFooterTitle:(id)footerTitle;
-(id)initWithHeaderTitle:(id)headerTitle;
-(id)init;
@end

