/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SCTableViewModelDelegate
@optional
-(id)tableViewModel:(id)model newImageNameForRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model detailViewDidDisappearForRowAtIndexPath:(id)detailView;
-(void)tableViewModel:(id)model detailViewWillAppearForRowAtIndexPath:(id)detailView withDetailTableViewModel:(id)detailTableViewModel;
-(void)tableViewModel:(id)model willRemoveRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model didInsertRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model returnButtonTappedForRowAtIndexPath:(id)indexPath;
-(BOOL)tableViewModel:(id)model valueIsValidForRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model valueChangedForRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model accessoryButtonTappedForRowWithIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model didDeselectRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model didSelectRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model willSelectRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model willDisplayCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model willConfigureCell:(id)cell forRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model itemEditedForSectionAtIndexPath:(id)indexPath item:(id)item;
-(void)tableViewModel:(id)model itemAddedForSectionAtIndexPath:(id)indexPath item:(id)item;
-(void)tableViewModel:(id)model itemCreatedForSectionAtIndex:(unsigned)index item:(id)item;
-(void)tableViewModel:(id)model detailViewDidDisappearForSectionAtIndex:(unsigned)detailView;
-(void)tableViewModel:(id)model detailViewWillAppearForSectionAtIndex:(unsigned)detailView withDetailTableViewModel:(id)detailTableViewModel;
-(void)tableViewModel:(id)model valueChangedForSectionAtIndex:(unsigned)index;
-(void)tableViewModelDidEndEditing:(id)tableViewModel;
-(void)tableViewModelWillEndEditing:(id)tableViewModel;
-(void)tableViewModelDidBeginEditing:(id)tableViewModel;
-(void)tableViewModelWillBeginEditing:(id)tableViewModel;
@end

