/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SCTableViewControllerDelegate
@optional
-(void)tableViewControllerWillDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerWillAppear:(id)tableViewController;
-(void)tableViewControllerDidDisappear:(id)tableViewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)tableViewControllerDidAppear:(id)tableViewController;
@end

