/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class SCBadgeView, NSString, SCTableViewModel, NSObject, NSArray;

__attribute__((visibility("hidden")))
@interface SCTableViewCell : UITableViewCell {
	id ownerViewControllerDelegate;
	SCTableViewModel* tempDetailModel;
	SCTableViewModel* ownerTableViewModel;
	id delegate;
	NSObject* boundObject;
	NSString* boundPropertyName;
	NSString* boundKey;
	NSObject* initialValue;
	BOOL coreDataBound;
	float height;
	BOOL editable;
	BOOL movable;
	BOOL selectable;
	BOOL autoResignFirstResponder;
	int cellEditingStyle;
	SCBadgeView* badgeView;
	NSString* detailViewTitle;
	int detailViewModalPresentationStyle;
	NSArray* detailCellsImageViews;
	BOOL detailViewHidesBottomBar;
	BOOL valueRequired;
	BOOL autoValidateValue;
	BOOL commitChangesLive;
	BOOL needsCommit;
	int detailTableViewStyle;
}
@property(retain, nonatomic) SCTableViewModel* tempDetailModel;
@property(retain, nonatomic) NSObject* boundValue;
@property(readonly, assign, nonatomic) BOOL needsCommit;
@property(assign, nonatomic) BOOL commitChangesLive;
@property(readonly, assign, nonatomic) BOOL valueIsValid;
@property(assign, nonatomic) BOOL autoValidateValue;
@property(assign, nonatomic) BOOL valueRequired;
@property(assign, nonatomic) int cellEditingStyle;
@property(assign, nonatomic) BOOL autoResignFirstResponder;
@property(assign, nonatomic) BOOL detailViewHidesBottomBar;
@property(retain, nonatomic) NSArray* detailCellsImageViews;
@property(assign, nonatomic) int detailTableViewStyle;
@property(assign, nonatomic) int detailViewModalPresentationStyle;
@property(copy, nonatomic) NSString* detailViewTitle;
@property(readonly, assign, nonatomic) SCBadgeView* badgeView;
@property(assign, nonatomic) BOOL selectable;
@property(assign, nonatomic) BOOL movable;
@property(assign, nonatomic) BOOL editable;
@property(assign, nonatomic) float height;
@property(readonly, assign, nonatomic) NSString* boundKey;
@property(readonly, assign, nonatomic) NSString* boundPropertyName;
@property(readonly, assign, nonatomic) NSObject* boundObject;
@property(assign, nonatomic) id delegate;
@property(assign, nonatomic) SCTableViewModel* ownerTableViewModel;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
+(id)cellWithText:(id)text;
+(id)cell;
-(void)enableOwnerViewControllerDelegate;
-(void)disableOwnerViewControllerDelegate;
-(void)setAttributesTo:(id)to;
-(void)reloadBoundValue;
-(void)commitChanges;
-(void)willDeselectCell;
-(void)didSelectCell;
-(void)willDisplay;
-(void)commitDetailModelChanges:(id)changes;
-(void)tempDetailModelModified;
-(void)cellValueChanged;
-(BOOL)getValueIsValid;
-(void)setBackgroundColor:(id)color;
-(void)layoutSubviews;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
-(id)initWithText:(id)text;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

