/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SCTableViewModelDataSource
@optional
-(id)tableViewModel:(id)model newItemForArrayOfItemsSectionAtIndex:(unsigned)index;
-(id)tableViewModel:(id)model sectionHeaderTitleForItem:(id)item AtIndex:(unsigned)index;
-(void)tableViewModel:(id)model moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(void)tableViewModel:(id)model commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(id)tableViewModel:(id)model customDetailViewForRowAtIndexPath:(id)indexPath;
-(id)tableViewModel:(id)model customDetailTableViewModelForRowAtIndexPath:(id)indexPath;
@end

