/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UITextFieldDelegate.h"
#import "SCControlCell.h"

@class UITextField;

__attribute__((visibility("hidden")))
@interface SCTextFieldCell : SCControlCell <UITextFieldDelegate> {
}
@property(readonly, assign, nonatomic) UITextField* textField;
+(id)cellWithText:(id)text withPlaceholder:(id)placeholder withBoundKey:(id)boundKey withTextFieldTextValue:(id)textFieldTextValue;
+(id)cellWithText:(id)text withPlaceholder:(id)placeholder withBoundObject:(id)boundObject withTextFieldTextPropertyName:(id)textFieldTextPropertyName;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)textFieldDidBeginEditing:(id)textField;
-(void)textFieldEditingChanged;
-(BOOL)getValueIsValid;
-(void)setAttributesTo:(id)to;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(void)setBackgroundColor:(id)color;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)dealloc;
-(id)initWithText:(id)text withPlaceholder:(id)placeholder withBoundKey:(id)boundKey withTextFieldTextValue:(id)textFieldTextValue;
-(id)initWithText:(id)text withPlaceholder:(id)placeholder withBoundObject:(id)boundObject withTextFieldTextPropertyName:(id)textFieldTextPropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

