/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITextView.h>
#import "Textastic-Structs.h"


__attribute__((visibility("hidden")))
@interface SCTextView : UITextView {
	float maxHeight;
}
@property(assign, nonatomic) float maxHeight;
-(void)setContentInset:(UIEdgeInsets)inset;
-(void)setContentOffset:(CGPoint)offset;
@end

