/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"


__attribute__((visibility("hidden")))
@interface SCTextViewAttributes : SCPropertyAttributes {
	float minimumHeight;
	float maximumHeight;
	BOOL editable;
	BOOL autoResize;
}
@property(assign, nonatomic) BOOL editable;
@property(assign, nonatomic) BOOL autoResize;
@property(assign, nonatomic) float maximumHeight;
@property(assign, nonatomic) float minimumHeight;
+(id)attributesWithMinimumHeight:(float)minimumHeight maximumHeight:(float)height autoResize:(BOOL)resize editable:(BOOL)editable;
-(void)dealloc;
-(id)initWithMinimumHeight:(float)minimumHeight maximumHeight:(float)height autoResize:(BOOL)resize editable:(BOOL)editable;
-(id)init;
@end

