/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "UITextViewDelegate.h"
#import "SCControlCell.h"

@class UITextView;

__attribute__((visibility("hidden")))
@interface SCTextViewCell : SCControlCell <UITextViewDelegate> {
	BOOL autoResize;
	float minimumHeight;
	float maximumHeight;
	BOOL initializing;
}
@property(assign, nonatomic) float maximumHeight;
@property(assign, nonatomic) float minimumHeight;
@property(assign, nonatomic) BOOL autoResize;
@property(readonly, assign, nonatomic) UITextView* textView;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withTextViewTextValue:(id)textViewTextValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withTextViewTextPropertyName:(id)textViewTextPropertyName;
-(void)textViewDidChange:(id)textView;
-(void)textViewDidBeginEditing:(id)textView;
-(void)layoutTextView;
-(BOOL)getValueIsValid;
-(void)setAttributesTo:(id)to;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(void)setBackgroundColor:(id)color;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(float)height;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withTextViewTextValue:(id)textViewTextValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withTextViewTextPropertyName:(id)textViewTextPropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

