/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCPropertyAttributes.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SCTextFieldAttributes : SCPropertyAttributes {
	NSString* placeholder;
}
@property(copy, nonatomic) NSString* placeholder;
+(id)attributesWithPlaceholder:(id)placeholder;
-(void)dealloc;
-(id)initWithPlaceholder:(id)placeholder;
-(id)init;
@end

