/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCControlCell.h"

@class ABUpDownControl;

__attribute__((visibility("hidden")))
@interface SCUpDownCell : SCControlCell {
}
@property(readonly, assign, nonatomic) ABUpDownControl* upDownControl;
+(id)cellWithText:(id)text withBoundKey:(id)boundKey withUpDownValue:(id)upDownValue;
+(id)cellWithText:(id)text withBoundObject:(id)boundObject withUpDownValuePropertyName:(id)upDownValuePropertyName;
-(void)upDownValueChanged;
-(void)commitChanges;
-(void)loadBoundValueIntoControl;
-(void)layoutSubviews;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withValue:(id)value;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withPropertyName:(id)propertyName;
-(void)dealloc;
-(id)initWithText:(id)text withBoundKey:(id)boundKey withUpDownValue:(id)upDownValue;
-(id)initWithText:(id)text withBoundObject:(id)boundObject withUpDownValuePropertyName:(id)upDownValuePropertyName;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

