/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>

@class UINavigationBar, SCTableViewModel, UIBarButtonItem, UITableView;

__attribute__((visibility("hidden")))
@interface SCViewController : UIViewController {
	BOOL toolbarAdded;
	UIViewController* ownerViewController;
	id delegate;
	UITableView* tableView;
	SCTableViewModel* tableViewModel;
	int navigationBarType;
	UINavigationBar* navigationBar;
	UIBarButtonItem* addButton;
	UIBarButtonItem* cancelButton;
	UIBarButtonItem* doneButton;
	BOOL cancelButtonTapped;
	BOOL doneButtonTapped;
}
@property(assign, nonatomic) UIViewController* ownerViewController;
@property(assign, nonatomic) id delegate;
@property(readonly, assign, nonatomic) BOOL doneButtonTapped;
@property(readonly, assign, nonatomic) BOOL cancelButtonTapped;
@property(readonly, assign, nonatomic) UIBarButtonItem* doneButton;
@property(readonly, assign, nonatomic) UIBarButtonItem* cancelButton;
@property(readonly, assign, nonatomic) UIBarButtonItem* editButton;
@property(readonly, assign, nonatomic) UIBarButtonItem* addButton;
@property(assign, nonatomic) int navigationBarType;
@property(retain, nonatomic) SCTableViewModel* tableViewModel;
@property(retain, nonatomic) UITableView* tableView;
-(void)dismissWithCancelValue:(BOOL)cancelValue doneValue:(BOOL)value;
-(void)doneButtonAction;
-(void)cancelButtonAction;
-(void)dealloc;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)awakeFromNib;
-(id)init;
@end

