/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SCViewControllerDelegate
@optional
-(void)viewControllerWillDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerWillAppear:(id)viewController;
-(void)viewControllerDidDisappear:(id)viewController cancelButtonTapped:(BOOL)tapped doneButtonTapped:(BOOL)tapped3;
-(void)viewControllerDidAppear:(id)viewController;
@end

