/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "Textastic-Structs.h"
#import <UIKit/UIViewController.h>
#import "UITextFieldDelegate.h"

@class UITextField, ABCodeEditorContentView, UIView, UISegmentedControl, SMTEDelegateController, UIBarButtonItem, UITableView;

__attribute__((visibility("hidden")))
@interface SearchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate> {
	UISegmentedControl* searchReplaceControl;
	UIBarButtonItem* searchReplaceBarButtonItem;
	UIBarButtonItem* settingsButton;
	UITableView* tableView;
	UIView* highlightedResult;
	UIView* topBackgroundView;
	float topControlsHeight;
	float topControlsHeightWithReplace;
	UIBarButtonItem* replaceAllButton;
	UIBarButtonItem* doneButton;
	ABCodeEditorContentView* _editorView;
	BOOL _replaceEnabled;
	BOOL _wholeWords;
	BOOL _caseSensitive;
	BOOL _diacriticSensitive;
	BOOL _regularExpression;
	UITextField* _searchTextField;
	UITextField* _replaceTextField;
	SMTEDelegateController* _textExpanderDelegate;
}
@property(readonly, assign, nonatomic) SMTEDelegateController* textExpanderDelegate;
@property(readonly, assign, nonatomic) UITextField* replaceTextField;
@property(readonly, assign, nonatomic) UITextField* searchTextField;
@property(assign, nonatomic) BOOL regularExpression;
@property(assign, nonatomic) BOOL diacriticSensitive;
@property(assign, nonatomic) BOOL caseSensitive;
@property(assign, nonatomic) BOOL wholeWords;
@property(assign, nonatomic) BOOL replaceEnabled;
@property(retain, nonatomic) ABCodeEditorContentView* editorView;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)doneButtonAction:(id)action;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)highlightRange:(NSRange)range;
-(void)replaceAllAction:(id)action;
-(void)replaceButtonPressed:(id)pressed;
-(void)removeHighlightedResult;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)maskImage:(id)image withMask:(id)mask;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)settingsAction:(id)action;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)textDidChange:(id)text;
-(void)clearSearch;
-(void)doSearch;
-(id)stringByUnescapingCharacters:(id)characters;
-(void)viewDidLoad;
-(void)searchReplaceModeChangedAction:(id)action;
-(void)refreshContentSizeInPopover;
-(bool)isInReplaceMode;
-(void)insertText:(id)text inTextField:(id)textField;
@end

