/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewModelDelegate.h"
#import "SCTableViewController.h"

@class SearchViewController;

__attribute__((visibility("hidden")))
@interface SearchSettingsViewController : SCTableViewController <SCTableViewModelDelegate> {
	SearchViewController* searchViewController;
}
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)initWithSearchViewController:(id)searchViewController;
-(void)tableViewModel:(id)model valueChangedForRowAtIndexPath:(id)indexPath;
@end

