/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"

@class NSArray;
@protocol SelectStringEncodingViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SelectStringEncodingViewController : SCTableViewController {
	NSArray* encodingDescriptions;
	NSArray* encodingValues;
	unsigned defaultEncoding;
	id<SelectStringEncodingViewControllerDelegate> selectStringEncodingViewControllerDelegate;
	int encodingIndex;
}
@property(copy, nonatomic) NSArray* encodingValues;
@property(copy, nonatomic) NSArray* encodingDescriptions;
@property(assign, nonatomic) id<SelectStringEncodingViewControllerDelegate> selectStringEncodingViewControllerDelegate;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType defaultEncoding:(BOOL)encoding;
-(void)doneButtonAction;
-(void)generateEncodingArrays;
@end

