/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"

@protocol SelectLineEndingTypeViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface SelectLineEndingTypeViewController : SCTableViewController {
	id<SelectLineEndingTypeViewControllerDelegate> selectLineEndingTypeViewControllerDelegate;
}
@property(assign, nonatomic) id<SelectLineEndingTypeViewControllerDelegate> selectLineEndingTypeViewControllerDelegate;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType defaultLineEndingType:(int)type;
-(void)doneButtonAction;
@end

