/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "NSCopying.h"
#import "NSCoding.h"
#import "NSMutableCopying.h"
#import "Textastic-Structs.h"

@class NSDictionary, SMTESnippetGroup, NSDate, NSString, NSArray, NSNumber, NSData;

@interface SMTESnippet : NSObject <NSCoding, NSCopying, NSMutableCopying> {
	NSString* abbreviation;
	NSString* plainText;
	NSData* richText;
	NSString* label;
	NSDate* creationDate;
	NSDate* modificationDate;
	int abbreviationMode;
	NSString* uuidString;
	unsigned flags;
	NSDictionary* extraInfo;
	unsigned snippetType;
	NSDate* lastUsed;
	unsigned useCount;
	NSData* cachedPNGImage;
	NSString* groupUUIDString;
	SMTESnippetGroup* group;
	BOOL hasUnwantedCharacters;
	BOOL shouldAbandonDelimiter;
	BOOL shouldRetainDelimiter;
	BOOL valid;
	NSArray* cursor;
	NSString* warning;
	NSNumber* lastMenuItemWidth;
	BOOL observing;
}
+(void)setGlobalAbbreviationModeIgnoresCase:(BOOL)aCase;
+(id)teSnippetErrorForAbbreviation:(id)abbreviation withMode:(int)mode optionalExistingSnippet:(id)snippet;
+(id)fromPlist:(id)plist;
-(id)init;
-(void)clearZeroCharacters;
-(id)initWithDictionary:(id)dictionary fromImport:(BOOL)import;
-(id)initWithSyncRecord:(id)syncRecord;
-(void)dealloc;
-(void)observe;
-(void)doneObserving;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(id)abbreviation;
-(id)richText;
-(void)setSnippetType:(unsigned)type;
-(unsigned)snippetType;
-(id)labelForSort;
-(void)setLabelForSort:(id)sort;
-(id)label;
-(int)abbreviationMode;
-(void)setAbbreviationMode:(int)mode;
-(void)setAbbreviation:(id)abbreviation;
-(BOOL)canDelete;
-(BOOL)writable;
-(void)setGroup:(id)group;
-(id)defaultLabel;
-(BOOL)isFormattedSnippet;
-(void)setIsFormattedSnippet:(BOOL)snippet;
-(id)snippets;
-(id)filteredSnippets;
-(void)setSnippets:(id)snippets;
-(id)UIDString;
-(id)snippetAbbreviation;
-(void)setSnippetAbbreviation:(id)abbreviation;
-(void)clearWarning;
-(BOOL)isEqual:(id)equal;
-(id)teSnippetAbbreviationError;
-(id)plainSnippetReplacementWithSimplifications:(BOOL)simplifications;
-(id)plainSnippetReplacementWithSimplifications;
-(id)formattedSnippetReplacementData;
-(void)setPlainSnippetReplacement:(id)replacement;
-(void)setSnippetAbbreviationMode:(int)mode;
-(BOOL)teHasValidSnippetAbbreviation;
-(id)group;
-(unsigned long)flags;
-(void)setFlags:(unsigned long)flags;
-(unsigned long)useCount;
-(id)lastUsed;
-(void)setUseCount:(unsigned long)count;
-(id)shellScript;
-(id)description;
-(id)keysToSync;
-(id)keysToStore;
-(id)keysToDuplicate;
-(void)updateFromDictionary:(id)dictionary;
-(id)syncRecord;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)copyWithZone:(NSZone*)zone;
-(id)plist;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(id)sourceString;
-(id)name;
-(id)lastUpdateInfo;
-(BOOL)syncWithDotMac;
-(unsigned long)updateFrequency;
-(id)groupSaveDuplicateTitle;
-(id)groupPrintTitle;
-(BOOL)suggestAbbreviations;
@end

