/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSDate, NSString, NSMutableArray, NSMutableDictionary, NSArray, NSRecursiveLock;

@interface SMTESnippetsController : NSObject {
	NSMutableArray* snippetGroups;
	NSMutableDictionary* settings;
	NSArray* currentSortDescriptors;
	NSString* currentFilter;
	BOOL readingSettings;
	NSRecursiveLock* transactionLock;
	int transactionLevel;
	NSDate* lastTransactionTime;
	id treeController;
	NSDate* settingsLastLoaded;
}
+(id)snippetsController;
-(id)settingsURL;
-(id)groupsProxyURL;
-(BOOL)saveSettingsToMobileDevice:(id)mobileDevice onQuit:(BOOL)quit;
-(void)setSettingsLastLoaded:(id)loaded;
-(id)settingsLastLoaded;
-(id)copySettingsFromMobileDevice;
-(void)awakeFromNib;
-(void)appWillTerminate:(id)app;
-(id)init;
-(void)dealloc;
-(id)snippetGroups;
-(id)snippetsForAbbreviation:(id)abbreviation;
-(BOOL)hasValidSnippetFor:(id)aFor;
-(id)allSnippets;
-(id)groupByUUID:(id)uuid;
-(id)snippetByUUID:(id)uuid;
-(void)removeSnippetWithUUID:(id)uuid;
-(void)removeGroupWithUUID:(id)uuid;
-(void)deleteGroup:(id)group;
-(void)importSnippets:(id)snippets toGroup:(id)group readOnly:(BOOL)only expansionMode:(int)mode canSelectWords:(BOOL)words;
-(void)clearSettings;
-(id)filteredSnippetGroups;
-(void)setFilteredSnippetGroups:(id)groups;
-(void)setFilter:(id)filter;
-(id)filter;
-(BOOL)load;
-(void)setSettings:(id)settings;
-(id)settings:(id)settings;
-(id)settings;
-(void)setSortDescriptors:(id)descriptors;
-(id)sortDescriptors;
-(void)saveTo:(id)to immediately:(BOOL)immediately;
-(void)beginSettingsTransaction;
-(void)completeTransactionSaveAndNotify:(unsigned long)notify;
-(void)completeTransactionNoSave;
-(void)singleValueTransaction:(id)transaction forSetting:(id)setting notify:(unsigned long)notify;
-(void)singleValueNoNotifyTransaction:(id)transaction forSetting:(id)setting;
-(void)singleValueNoSave:(id)save forSetting:(id)setting;
-(void)implicitTransactionSave;
-(id)recentTransactionTimestamp;
-(BOOL)isWithinTransaction;
-(BOOL)appendSnippetsFromTextFile:(id)textFile defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy;
-(BOOL)appendSnippetsFromDictionary:(id)dictionary defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy withName:(id)name;
-(BOOL)appendSnippetsFromDictionaryData:(id)dictionaryData defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy withName:(id)name;
-(BOOL)appendSnippetsFromDictionaryFile:(id)dictionaryFile defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy;
-(BOOL)appendSnippetsFromTypeIt4MeFile:(id)typeIt4MeFile defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy;
-(BOOL)appendSnippetsFromFile:(id)file defaultAbbreviationMode:(int)mode localCopy:(BOOL)copy;
-(BOOL)importSnippetsFromFiles:(id)files defaultAbbreviationMode:(int)mode;
-(unsigned)totalNumberOfSnippets;
-(unsigned)correctedTotalNumberOfSnippets;
-(void)addGroupFromDownload:(id)download at:(id)at replace:(id)replace;
-(void)addGroupFromDownload:(id)download at:(id)at;
-(void)addGroupFromFile:(id)file localCopy:(BOOL)copy replace:(id)replace;
-(void)addGroupFromData:(id)data withName:(id)name;
-(void)addGroupFromFile:(id)file localCopy:(BOOL)copy;
-(void)addGroupFromPlist:(id)plist;
-(void)clearWarnings;
-(BOOL)boolForSetting:(id)setting;
-(int)integerForSetting:(id)setting;
-(id)valueForSetting:(id)setting;
-(void)setValue:(id)value forSetting:(id)setting;
-(void)setBool:(BOOL)aBool forSetting:(id)setting;
-(id)treeController;
@end

