/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "NSCopying.h"
#import "NSMutableCopying.h"
#import <Foundation/NSObject.h>

@class NSDate, NSString, NSMutableArray, NSMutableDictionary, NSArray;

@interface SMTESnippetGroup : NSObject <NSCopying, NSMutableCopying> {
	NSString* name;
	NSMutableArray* snippets;
	BOOL writable;
	BOOL suggestAbbreviations;
	NSString* source;
	NSString* uuidString;
	unsigned sourceType;
	unsigned updateFrequency;
	NSDate* lastUpdate;
	NSString* soundPreference;
	NSMutableArray* expanderExceptions;
	int expanderExceptionsMode;
	NSArray* snippetUUIDs;
	NSString* filter;
	NSMutableDictionary* sensitiveAbbrevs;
	NSMutableDictionary* agnosticAbbrevs;
	BOOL snippetsMenuNeedsUpdate;
	unsigned expandAfterMode;
	NSMutableArray* filteredSnippets;
	BOOL observingName;
	BOOL observingSnippets;
}
+(id)keysToStore;
+(id)fromPlist:(id)plist;
-(id)init;
-(id)initWithSyncRecord:(id)syncRecord;
-(void)doneObserving;
-(void)doneObservingSnippets;
-(void)dealloc;
-(id)snippets;
-(int)snippetCount;
-(id)filteredSnippets:(BOOL)snippets;
-(id)filteredSnippets;
-(void)setFilteredSnippets:(id)snippets;
-(void)updateFromDictionary:(id)dictionary;
-(void)setFilter:(id)filter;
-(BOOL)canDelete;
-(BOOL)writable;
-(id)description;
-(void)observe;
-(void)redoCaches;
-(BOOL)changeAbbreviationFor:(id)aFor to:(id)to;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(id)agnosticAbbrevs;
-(void)addSnippet:(id)snippet;
-(void)deleteSnippet:(id)snippet;
-(void)changeSnippet:(id)snippet abbreviationTo:(id)to;
-(void)abbreviationModeChanged:(id)changed;
-(BOOL)expandAfterSucceedsWithin:(id)within forSnippet:(id)snippet;
-(id)snippetForAbbreviation:(id)abbreviation keys:(id)keys lowercaseKeys:(id)keys3;
-(void)collectSnippetsMatching:(id)matching;
-(id)plist;
-(id)plistWithSnippets;
-(BOOL)exportTo:(id)to;
-(id)copyWithZone:(NSZone*)zone;
-(void)setAgnosticAbbrevs:(id)abbrevs;
-(void)setSensitiveAbbrevs:(id)abbrevs;
-(id)mutableCopyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(BOOL)doesSync;
-(id)syncRecord;
-(id)lastModified;
-(unsigned)expandAfterMode;
-(void)setExpandAfterMode:(unsigned)mode;
-(id)UIDString;
-(id)lastUsed;
-(unsigned long)useCount;
-(id)plainSnippetReplacementWithSimplifications;
-(id)creationDate;
-(id)modificationDate;
-(id)label;
-(void)setLabel:(id)label;
-(id)abbreviation;
-(void)setAbbreviation:(id)abbreviation;
-(id)labelForSort;
-(void)setLabelForSort:(id)sort;
-(BOOL)isEqual:(id)equal;
-(BOOL)isFormattedSnippet;
-(void)setIsFormattedSnippet:(BOOL)snippet;
-(int)abbreviationMode;
-(unsigned)snippetType;
-(void)setAbbreviationMode:(int)mode;
-(unsigned long)sourceType;
-(void)setSource:(id)source;
-(id)sourceString;
-(id)name;
-(int)expanderExceptionsMode;
-(void)setExpanderExceptionsMode:(id)mode;
-(id)groupSaveDuplicateTitle;
-(id)groupPrintTitle;
-(id)lastUpdateInfo;
-(BOOL)suggestAbbreviations;
-(void)setSuggestAbbreviations:(BOOL)abbreviations;
@end

