/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "Textastic-Structs.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface SSZipArchive : NSObject {
	NSString* _path;
	NSString* _filename;
	void* _zip;
}
+(id)_dateWithMSDOSFormat:(unsigned long)msdosformat;
+(BOOL)createZipFileAtPath:(id)path withFilesAtPaths:(id)paths;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password error:(id*)error delegate:(id)delegate;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination delegate:(id)delegate;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination overwrite:(BOOL)overwrite password:(id)password error:(id*)error;
+(BOOL)unzipFileAtPath:(id)path toDestination:(id)destination;
+(BOOL)isValidZipFileAtPath:(id)path;
-(BOOL)close;
-(BOOL)writeData:(id)data filename:(id)filename;
-(BOOL)writeFile:(id)file;
-(void)zipInfo:(XXStruct_z_NMMB*)info setDate:(id)date;
-(BOOL)open;
-(void)dealloc;
-(id)initWithPath:(id)path;
@end

