/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import "NSObject.h"


@protocol SSZipArchiveDelegate <NSObject>
@optional
-(void)zipArchiveDidUnzipFileAtIndex:(int)zipArchive totalFiles:(int)files archivePath:(id)path fileInfo:(unz_file_info_s)info;
-(void)zipArchiveWillUnzipFileAtIndex:(int)zipArchive totalFiles:(int)files archivePath:(id)path fileInfo:(unz_file_info_s)info;
-(void)zipArchiveDidUnzipArchiveAtPath:(id)zipArchive zipInfo:(unz_global_info_s)info unzippedPath:(id)path;
-(void)zipArchiveWillUnzipArchiveAtPath:(id)zipArchive zipInfo:(unz_global_info_s)info;
@end

