/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UITableViewController.h>
#import "UISearchDisplayDelegate.h"

@class UISearchDisplayController, NSMutableArray, UIView, NSArray, UISearchBar;

__attribute__((visibility("hidden")))
@interface SymbolListViewController : UITableViewController <UISearchDisplayDelegate> {
	UIView* highlightedResult;
	NSMutableArray* _symbolMappingArray;
	UISearchBar* _searchBar;
	UISearchDisplayController* _searchController;
	NSMutableArray* _filteredList;
	NSArray* _symbolList;
}
@property(retain, nonatomic) NSArray* symbolList;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)highlightRange:(NSRange)range;
-(void)removeHighlightedResult;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(void)dealloc;
-(id)bestImageForSymbol:(id)symbol;
-(id)initWithStyle:(int)style;
-(void)addSymbolMappingWithScopeSelectorString:(id)scopeSelectorString imageName:(id)name;
@end

