/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UIResponder.h>
#import "UIApplicationDelegate.h"

@class EditorViewController, UINavigationController, FileTableViewController, FMWebDAVRequest, FileTransferViewController, UIWindow, WebDAVServer;

__attribute__((visibility("hidden")))
@interface TextasticAppDelegate : UIResponder <UIApplicationDelegate> {
	BOOL needsRefreshWhenBecomingActive;
	BOOL needsStartServerWhenBecomingActive;
	BOOL urlOpened;
	BOOL launching;
	WebDAVServer* _webDAVServer;
	FMWebDAVRequest* _request;
	UIWindow* _window;
	UINavigationController* _navigationController;
	EditorViewController* _editorViewController;
	FileTableViewController* _fileTableViewController;
	FileTransferViewController* _fileTransferViewController;
}
@property(readonly, assign, nonatomic) FileTransferViewController* fileTransferViewController;
@property(readonly, assign, nonatomic) FileTableViewController* fileTableViewController;
@property(readonly, assign, nonatomic) WebDAVServer* webDAVServer;
@property(retain, nonatomic) EditorViewController* editorViewController;
@property(retain, nonatomic) UINavigationController* navigationController;
@property(retain, nonatomic) UIWindow* window;
-(void)switchToLocalPath:(id)localPath;
-(void)presentFileTransferViewController;
-(void)refreshFileTableViewController;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)checkLockApplication;
-(BOOL)application:(id)application handleOpenURL:(id)url;
-(BOOL)application:(id)application openURL:(id)url sourceApplication:(id)application3 annotation:(id)annotation;
-(id)fileNameFromURL:(id)url;
-(id)sanitizeFileNameString:(id)string;
-(BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
-(void)setupGreenButton:(id)button;
-(void)setupDoneButton:(id)button done:(BOOL)done;
-(void)setupNavigationBar:(id)bar translucent:(BOOL)translucent;
-(void)setupCustomAppearance;
-(void)setupSegmentedControlAppearanceWithAppearanceProxy:(id)appearanceProxy;
-(void)setupToolbarAppearanceWithAppearanceProxy:(id)appearanceProxy;
-(void)setupBarButtonItemAppearanceWithAppearanceProxy:(id)appearanceProxy;
-(void)dealloc;
@end

