/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

typedef struct {
	unsigned long _field1;
	id* _field2;
	unsigned long* _field3;
	unsigned long _field4[5];
} XXStruct_kFm5bA;

typedef struct _NSRange {
	unsigned location;
	unsigned length;
} NSRange;

typedef struct unz_global_info_s {
	unsigned _field1;
	unsigned _field2;
} unz_global_info_s;

typedef struct tm_unz_s {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
} tm_unz_s;

typedef struct unz_file_info_s {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	unsigned _field9;
	unsigned _field10;
	unsigned _field11;
	unsigned _field12;
	unsigned _field13;
	unsigned _field14;
	tm_unz_s _field15;
} unz_file_info_s;

typedef struct tm_zip_s {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
} tm_zip_s;

typedef struct {
	tm_zip_s _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned _field4;
} XXStruct_z_NMMB;

typedef struct JKHashTableEntry {
	unsigned _field1;
	id _field2;
	id _field3;
} JKHashTableEntry;

typedef struct JKConstPtrRange {
	char* _field1;
	unsigned _field2;
} JKConstPtrRange;

typedef struct JKConstBuffer {
	JKConstPtrRange _field1;
} JKConstBuffer;

typedef struct JKTokenCacheItem* JKTokenCacheItemRef;

typedef struct JKTokenValue {
	JKConstPtrRange _field1;
	unsigned _field2;
	unsigned _field3;
	union {
		long long _field1;
		unsigned long long _field2;
		double _field3;
	} _field4;
	JKTokenCacheItemRef _field5;
} JKTokenValue;

typedef struct JKPtrRange {
	char* _field1;
	unsigned _field2;
} JKPtrRange;

typedef struct JKManagedBuffer {
	JKPtrRange _field1;
	unsigned _field2;
	unsigned _field3;
} JKManagedBuffer;

typedef struct JKParseToken {
	JKConstPtrRange _field1;
	unsigned _field2;
	JKTokenValue _field3;
	JKManagedBuffer _field4;
} JKParseToken;

typedef struct JKObjectStack {
	void** _field1;
	void** _field2;
	unsigned* _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
	unsigned _field7;
} JKObjectStack;

typedef struct JKTokenCache {
	JKTokenCacheItemRef _field1;
	unsigned _field2;
	unsigned _field3;
	unsigned char _field4[1024];
} JKTokenCache;

typedef struct JKObjCImpCache {
	Class _field1;
	/*function-pointer*/ void* _field2;
	/*function-pointer*/ void* _field3;
} JKObjCImpCache;

typedef struct JKParseState {
	unsigned _field1;
	JKConstBuffer _field2;
	unsigned _field3;
	unsigned _field4;
	unsigned _field5;
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	JKParseToken _field9;
	JKObjectStack _field10;
	JKTokenCache _field11;
	JKObjCImpCache _field12;
	id _field13;
	int _field14;
	BOOL _field15;
} JKParseState;

typedef struct JKFastClassLookup {
	void* _field1;
	void* _field2;
	void* _field3;
	void* _field4;
	void* _field5;
} JKFastClassLookup;

typedef struct JKEncodeCache {
	id _field1;
	unsigned _field2;
	unsigned _field3;
} JKEncodeCache;

typedef struct JKEncodeState {
	JKManagedBuffer _field1;
	JKManagedBuffer _field2;
	unsigned _field3;
	JKFastClassLookup _field4;
	JKEncodeCache _field5[1024];
	unsigned _field6;
	unsigned _field7;
	unsigned _field8;
	id _field9;
	id _field10;
	SEL _field11;
	/*function-pointer*/ void* _field12;
	id _field13;
	/*function-pointer*/ void _field14;
} JKEncodeState;

typedef struct UIEdgeInsets {
	float top;
	float left;
	float bottom;
	float right;
} UIEdgeInsets;

typedef struct sqlite3 sqlite3;

typedef struct sqlite3_stmt sqlite3_stmt;

typedef struct dispatch_queue_s dispatch_queue_s;

typedef struct CGAffineTransform {
	float a;
	float b;
	float c;
	float d;
	float tx;
	float ty;
} CGAffineTransform;

typedef struct __sFILE sFILE;

typedef struct {
	void* _field1;
	id _field2;
	int _field3;
	id _field4;
	id _field5;
	id _field6;
	sFILE* _field7;
	sFILE* _field8;
	id _field9;
	id _field10;
	id _field11;
	id _field12;
	id _field13;
	sFILE* _field14;
} XXStruct_pfqgTA;

typedef struct {
	id _field1;
	int _field2;
	id _field3;
	id _field4;
	id _field5;
} XXStruct_MT0nvC;

typedef struct re_pattern_buffer re_pattern_buffer;
typedef struct OnigEncodingTypeST OnigEncodingTypeST;
typedef struct re_pattern_buffer {
	char* _field1;
	unsigned _field2;
	unsigned _field3;
	int _field4;
	int _field5;
	int _field6;
	int _field7;
	int _field8;
	int _field9;
	unsigned _field10;
	unsigned _field11;
	unsigned _field12;
	int _field13;
	int _field14;
	CGPoint* _field15;
	OnigEncodingTypeST* _field16;
	unsigned _field17;
	CGPoint* _field18;
	unsigned _field19;
	void* _field20;
	int _field21;
	int _field22;
	int _field23;
	unsigned _field24;
	unsigned _field25;
	int _field26;
	char* _field27;
	char* _field28;
	unsigned char _field29[256];
	int* _field30;
	int* _field31;
	unsigned _field32;
	unsigned _field33;
	re_pattern_buffer* _field34;
} re_pattern_buffer;

struct OnigEncodingTypeST OnigEncodingTypeST;

struct re_pattern_buffer re_pattern_buffer;

typedef struct OnigCaptureTreeNodeStruct OnigCaptureTreeNodeStruct;

typedef struct re_registers {
	int _field1;
	int _field2;
	int* _field3;
	int* _field4;
	OnigCaptureTreeNodeStruct* _field5;
} re_registers;

typedef struct {
	unsigned _field1;
	unsigned _field2;
	unsigned _field3;
} XXStruct_VrsxJB;

typedef struct CGContext* CGContextRef;

typedef struct __CTLine* CTLineRef;

typedef struct __CTFramesetter* CTFramesetterRef;

typedef struct __CTFrame* CTFrameRef;

typedef struct __CFArray* CFArrayRef;

typedef struct {
	float cumulativeAverage;
	unsigned valueCount;
} XXStruct_DaUm_C;

typedef struct __CTFont* CTFontRef;

typedef struct __CTParagraphStyle* CTParagraphStyleRef;

typedef struct {
	id _field1;
	unsigned short _field2;
} XXStruct_c19r_A;


