/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UILabel, UIProgressView;

__attribute__((visibility("hidden")))
@interface TransferProgressTableViewCell : UITableViewCell {
	UILabel* fileNameLabel;
	UILabel* progressLabel;
	UILabel* pathLabel;
	UIProgressView* progressView;
}
+(float)rowHeight;
-(void)dealloc;
-(void)updateProgressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)setupCellWithFileInformation:(id)fileInformation;
-(void)setupCellWithRemoteFileInformation:(id)remoteFileInformation;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

