/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>
#import "RemoteConnectionDelegate.h"
#import "UIAlertViewDelegate.h"

@class UILabel, NSString, NSMutableArray, RemoteConnection;

__attribute__((visibility("hidden")))
@interface TransferProgressViewController : UITableViewController <RemoteConnectionDelegate, UIAlertViewDelegate> {
	NSMutableArray* arrayOfFileInformationToFetch;
	NSMutableArray* arrayOfFetchedFileInformation;
	RemoteConnection* connection;
	NSString* downloadTargetPath;
	NSString* downloadRemoteSourcePath;
	NSString* uploadSourcePath;
	NSString* uploadRemoteTargetPath;
	int mode;
	BOOL shouldCancel;
	int runningRetrievals;
	int fileCount;
	int directoryCount;
	int fileCountOverriddenByUpload;
	UILabel* statusLabel;
	BOOL quickTransfer;
	NSMutableArray* errorStrings;
	NSString* completeErrorString;
}
@property(assign, nonatomic) BOOL quickTransfer;
@property(copy, nonatomic) NSString* uploadRemoteTargetPath;
@property(copy, nonatomic) NSString* uploadSourcePath;
@property(copy, nonatomic) NSString* downloadRemoteSourcePath;
@property(copy, nonatomic) NSString* downloadTargetPath;
@property(retain, nonatomic) RemoteConnection* connection;
@property(assign, nonatomic) int mode;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)flexibleSpace;
-(void)cancelAction:(id)action;
-(void)remoteConnection:(id)connection createDirectory:(id)directory failedWithError:(id)error userData:(id)data;
-(void)remoteConnection:(id)connection didCreateDirectory:(id)directory userData:(id)data;
-(void)remoteConnection:(id)connection deleteFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didDeleteFile:(id)file;
-(void)remoteConnection:(id)connection uploadFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didUploadFile:(id)file;
-(void)remoteConnection:(id)connection didUploadFile:(id)file withError:(BOOL)error;
-(void)remoteConnection:(id)connection uploadFile:(id)file progressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)remoteConnection:(id)connection downloadFile:(id)file failedWithError:(id)error;
-(void)remoteConnection:(id)connection didDownloadFile:(id)file;
-(void)remoteConnection:(id)connection didDownloadFile:(id)file withError:(BOOL)error;
-(BOOL)showErrors;
-(void)remoteConnection:(id)connection downloadFile:(id)file progressTotal:(unsigned long long)total now:(unsigned long long)now;
-(id)cellForFileInformation:(id)fileInformation;
-(void)remoteConnection:(id)connection requestRemoteFileInformationArrayFailedWithError:(id)error;
-(void)remoteConnection:(id)connection didReceiveRemoteFileInformationArray:(id)array;
-(void)fetchNextFileInfo;
-(void)fetchNextRemoteFileInfo;
-(void)checkIfFilesWillGetOverriddenByUpload;
-(void)remoteConnection:(id)connection checkIfFileExistsAt:(id)at failedWithError:(id)error userData:(id)data;
-(void)remoteConnection:(id)connection fileAt:(id)at exists:(BOOL)exists userData:(id)data;
-(void)confirmDeletion;
-(void)showOverrideAlertForUpload;
-(void)checkIfFilesWillGetOverriddenByDownload;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)deleteFiles;
-(void)uploadFiles;
-(void)downloadFiles;
-(id)remoteTargetPathForFileInfo:(id)fileInfo;
-(id)localTargetPathForRemoteFileInfo:(id)remoteFileInfo;
-(void)enqueueFileInformationToFetch:(id)fetch;
-(void)enqueueRemoteFileInformationToFetch:(id)fetch;
-(void)setStatusLabelText:(id)text;
-(id)fileAndDirectoryCountString;
-(void)logError:(id)error forAction:(id)action;
-(void)dismissModalViewControllerAnimated:(BOOL)animated;
-(id)initWithStyle:(int)style;
@end

