/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableView.h>
#import "Textastic-Structs.h"


@interface UITableView (ModifiedBackground)
+(void)enableCustomBackground;
-(id)modifiedBackgroundInitWithFrame:(CGRect)frame style:(int)style;
-(void)setCustomBackground;
@end

