/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Textastic-Structs.h"
#import <UIKit/UITextField.h>


@interface UITextField (Selection)
-(NSRange)figureOutSelectedRange;
-(int)offsetFromTextPosition:(id)textPosition;
@end

