/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSThread.h>

@class WebDAVServer;

__attribute__((visibility("hidden")))
@interface WebDAVServerThread : NSThread {
	WebDAVServer* server;
}
@property(retain, nonatomic) WebDAVServer* server;
+(id)md5HexDigest:(id)digest;
-(void)dealloc;
-(void)main;
@end

