/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class WebDAVServerThread, NSString;

__attribute__((visibility("hidden")))
@interface WebDAVServer : NSObject {
	NSString* user;
	NSString* password;
	unsigned port;
	WebDAVServerThread* thread;
	BOOL started;
}
@property(readonly, assign, nonatomic, getter=isStarted) BOOL started;
@property(assign, nonatomic) unsigned port;
@property(copy, nonatomic) NSString* password;
@property(copy, nonatomic) NSString* user;
-(void)dealloc;
-(void)shutdownInBackground;
-(void)shutdown;
-(void)start;
-(void)saveSettings;
-(void)loadSettings;
-(id)init;
@end

