/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RemoteConnection.h"
#import "Textastic-Structs.h"

@class NSString, NSOperationQueue;

__attribute__((visibility("hidden")))
@interface WebDAVConnection : RemoteConnection {
	NSOperationQueue* queue;
	NSString* user;
	NSString* password;
	NSString* url;
	BOOL verifySSLCertificate;
}
@property(assign) BOOL verifySSLCertificate;
@property(copy) NSString* url;
@property(copy) NSString* password;
@property(copy) NSString* user;
-(id)configurationViewControllerWithMode:(int)mode andDelegate:(id)delegate;
-(id)titleForConnectionList;
-(id)navigationItemTitleForPath:(id)path;
-(void)renameFile:(id)file newFileName:(id)name withDelegate:(id)delegate;
-(void)deleteFile:(id)file withDelegate:(id)delegate;
-(void)checkIfFileExistsAt:(id)at withDelegate:(id)delegate userData:(id)data;
-(void)createDirectory:(id)directory withDelegate:(id)delegate userData:(id)data;
-(void)uploadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)downloadFile:(id)file toDirectory:(id)directory withDelegate:(id)delegate;
-(void)initializeConnectionUserData:(XXStruct_MT0nvC*)data requestType:(int)type delegate:(id)delegate;
-(void)request:(id)request sendProgressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)request:(id)request progressTotal:(unsigned long long)total now:(unsigned long long)now;
-(void)requestRemoteFileInformationArrayForSubdirectory:(id)subdirectory withDelegate:(id)delegate;
-(id)errorForRequest:(id)request;
-(id)buildSynchronousRequestForPath:(id)path withOperation:(id)operation;
-(id)urlForPath:(id)path;
-(id)baseURLString;
-(id)escapePath:(id)path;
-(id)cancelError;
-(void)cancelAllRequests;
-(void)loadConfigFromDictionary:(id)dictionary;
-(id)configDictionary;
-(int)remoteConnectionType;
-(void)dealloc;
-(id)init;
@end

