/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewModelDelegate.h"
#import "SCTableViewController.h"


__attribute__((visibility("hidden")))
@interface WebDAVViewController : SCTableViewController <SCTableViewModelDelegate> {
}
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(void)viewWillDisappear:(BOOL)view;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(id)initWithStyle:(int)style withNavigationBarType:(int)navigationBarType;
-(void)tableViewModel:(id)model valueChangedForRowAtIndexPath:(id)indexPath;
-(void)tableViewModel:(id)model didSelectRowAtIndexPath:(id)indexPath;
-(id)getIPAddress;
@end

