/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SCTableViewController.h"
#import "SCTableViewModelDelegate.h"

@class WebDAVConnection;
@protocol RemoteConnectionConfigurationDelegate;

__attribute__((visibility("hidden")))
@interface WebDAVConfigurationViewController : SCTableViewController <SCTableViewModelDelegate> {
	WebDAVConnection* connection;
	id<RemoteConnectionConfigurationDelegate> remoteConnectionConfigurationDelegate;
	int configurationMode;
}
@property(retain, nonatomic) WebDAVConnection* connection;
-(void)dealloc;
-(void)viewDidUnload;
-(void)didReceiveMemoryWarning;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)cancelButtonAction;
-(void)doneButtonAction;
-(id)initWithWebDAVConnection:(id)webDAVConnection mode:(int)mode delegate:(id)delegate;
@end

